### ISSUE TITLE
Arrange food, drink, and venue access for OKC OSH event | 01/13/2018 2:00 pm

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#100]
What: We are meeting to see your projects.
When: 01/13/2018 2:00 pm
Where: , 

Check meetup for RSVP count: https://www.meetup.com/OKC-OSH/events/fxtrmlyxcbrb/

**Comment by seejessicacode** [comment]
OKC OSH has recurring events turned on which makes Meetup trigger "create event" a year in advance and skip events that were already created and time of setting up their automation. I'm closing this and will turn off the food issue portion of their automation.
