### ISSUE TITLE
Request reimbursement for food and drink for Tulsa Web Devs event | 2018-07-03

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/user-groups#1005]
What: Techlahoma Hack Night
When: 2018-07-03 6:00 PM
Where: 36 East Cameron St., Tulsa

Check meetup for RSVP count: https://www.meetup.com/Tulsa-Web-Devs/events/nnqstpyxkbfb/

To request reimbursement, please complete the following steps:
- [x] Post picture of receipt(s) in this thread
- [x] Post photo(s) of the meetup in action on your meetup event
- [x] Submit [request for reimbursement](https://github.com/techlahoma/user-groups/wiki/Requesting-Reimbursement) from the Techlahoma Foundation on https://venmo.com within 1 month of the event

Any questions about reimbursement may be referred to the board treasurer.

cc @jdungan, @groovecoder

**Comment by groovecoder** [comment]
![image](https://user-images.githubusercontent.com/71928/42411061-b3dfb82e-81ba-11e8-809f-02310ecd7833.png)

**Comment by groovecoder** [comment]
![img_4208](https://user-images.githubusercontent.com/71928/42411073-1c571532-81bb-11e8-8284-13039e8b7ff2.JPG)
![img_4207](https://user-images.githubusercontent.com/71928/42411074-1c6f7f14-81bb-11e8-92a9-938c91ce3cb5.JPG)

**Comment by jsonthebson** [comment]
About 30 attendees per @groovecoder 

Paid, thanks.
