### ISSUE TITLE
OKC SQL is still listed as an Edmond Meetup group

### ISSUE THREAD

**Issue by Ava-SS46** [techlahoma/user-groups#101]

**Comment by kacollins** [comment]
Here are the instructions for changing a meetup location: https://www.meetup.com/help/topics/22/article/930770/

**Comment by seejessicacode** [comment]
We're holding off on any changes for OKC SQL until they make Techlahoma organizer.
https://www.meetup.com/OKCSQL/

**Comment by kacollins** [comment]
The Techlahoma groups in the OKC area are spread out on the [Meetup map](https://www.meetup.com/pro/Techlahoma/), with the Big Data group also showing up in Edmond.

![image](https://cloud.githubusercontent.com/assets/15042297/22001435/d1979226-dc0a-11e6-8f7f-eae87215f6c6.png)

I believe the location is coming from the ZIP code entered on the group's "Basics" page. I looked up the ZIP code for StarSpace46 and used it for the OKC OSH group, but the marker for OKC LUGnuts looks closest to the actual location. It would help to know what ZIP code they used.
