### ISSUE TITLE
Book StarSpace46 for OKC OSH | 02/11/2017 2:00 pm

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#104]
What: TBD
When: 02/11/2017 2:00 pm
Where: StarSpace 46

Check meetup for RSVP count: https://www.meetup.com/OKC-OSH/events/236925812/

cc @kacollins

**Comment by seejessicacode** [comment]
![snip20170117_4](https://cloud.githubusercontent.com/assets/943398/22026498/99910ed4-dc96-11e6-8da1-a655dfed4516.png)

**Comment by kacollins** [comment]
Would it be possible for us to use the event space instead of the Holodeck? We've had a request for the meetups to be live streamed. cc @Ava-SS46

**Comment by seejessicacode** [comment]
![snip20170117_1](https://cloud.githubusercontent.com/assets/943398/22041927/751c7fb0-dcce-11e6-9c44-2bec5a48a2e0.png)
