### ISSUE TITLE
January Techlahoma Townhall is not Booked

### ISSUE THREAD

**Issue by Ava-SS46** [techlahoma/user-groups#105]

**Comment by Ava-SS46** [comment]
Neither is the Board meeting

**Comment by kacollins** [comment]
Would it make sense to use the scheduling label for this, even though it's not for a user group?

**Comment by amandaharlin** [comment]
we need to hook up the automation rules to the techlahoma meetup. that'd
solve solve of these problems.

On Mon, Jan 16, 2017 at 12:36 PM, Kimberly Collins <notifications@github.com

**Comment by seejessicacode** [comment]
![snip20170117_2](https://cloud.githubusercontent.com/assets/943398/22026134/8db547e8-dc95-11e6-88e1-afe08e0bd1ca.png)

**Comment by seejessicacode** [comment]
![snip20170117_3](https://cloud.githubusercontent.com/assets/943398/22026227/d2d5d1a8-dc95-11e6-984e-ead9ebfd3abd.png)

**Comment by seejessicacode** [comment]
I'm of the mind that these need to be scheduled by the folks in charge of planning the board meetings and town halls and not the user group committee.
