### ISSUE TITLE
Request reimbursement for food and drink for Tulsa Hack Night event | 2018-08-07

### ISSUE THREAD

**Issue by chimchim237** [techlahoma/user-groups#1081]
What: Tulsa WebDevs: Techlahoma Hack Night
When: 2018-08-07 06:30 PM
Where: 36 E Cameron St, Tulsa

Check meetup for RSVP count: https://www.meetup.com/Tulsa-Web-Devs/events/nnqstpyxlbkb/

**Comment by chimchim237** [comment]
![screenshot_2018-08-07 your domino s order - tulsadesigner gmail com - gmail](https://user-images.githubusercontent.com/8526129/43802194-b3cf7b54-9a5a-11e8-932d-664f39379bad.png)

**Comment by jsonthebson** [comment]
What was the attendee count?
