### ISSUE TITLE
Email to non-meetup distribution list X days before event

### ISSUE THREAD

**Issue by rhoegg** [techlahoma/user-groups#109]
Some user groups such as [OKCJUG](http://www.okcjug.org/) may already have opt-in email lists that are used for announcements as well as discussion. It would be nice if meeting announcements could automatically go to those lists a configurable number of days before the meeting.

OKCJUG probably wants it to go out the Friday before the meeting, which is the second Tuesday of each month.

**Comment by seejessicacode** [comment]
@rhoegg Do I address the outgoing email announcement to jug@okcjug.org?

**Comment by seejessicacode** [comment]
Is there any preferred format I should keep in mind? Are there any special instructions I should include for folks who want to unsubscribe?

Last email I have ends with:
_______________________________________________
Jug mailing list
Jug@lists.okcjug.org
http://lists.okcjug.org/listinfo.cgi/jug-okcjug.org

**Comment by seejessicacode** [comment]
I got something in place but here's the template for your review:

To: jug@okcjug.org
From: techlahoma@gmail.com

Subject: OKC JUG Meeting: [Event date, MM/DD/YYYY]
Body:
Next meeting is scheduled for (Event datetime, MM/DD/YYYY h:mm a). Please RSVP at (meetup event url).

(Event description without the HTML)
_______________________________________________
Jug mailing list
Jug@lists.okcjug.org
http://lists.okcjug.org/listinfo.cgi/jug-okcjug.org

**Comment by seejessicacode** [comment]
Looks like it worked. So as long as OKC JUG posts a meetup before the Friday before the meetup, this email should go out. Ideally, all Techlahoma meetup events are created at least 2 weeks in advance.
 
![image](https://cloud.githubusercontent.com/assets/943398/24861243/aff61ab2-1dbd-11e7-8ed5-232c87d9c272.png)

Since I've received no response regarding format and email list address, I'm going to close this.

**Comment by rhoegg** [comment]
Thanks Jessica! Can you point me to where the code is for this? I might be
able to update the template to match what we're sending out every month by
hand.

**Comment by seejessicacode** [comment]
There is no code. This was all set through Zapier. I've ask about template in the past in the past and received no feedback, so I just guessed.

**Comment by rhoegg** [comment]
OK, and thanks for doing that. How can I update Zapier?

**Comment by seejessicacode** [comment]
You can't. You will have to tell me or someone else on the UG committee what you want the template to be.

**Comment by rhoegg** [comment]
Ah OK.  Next hack night we should look at how to do something like pull
requests for the integrations.

Our October meeting announcement is probably a good template.

Subject: [OKCJUG] October 11 Meeting: Find Data in the Blink of an Eye

When: October 11, 2016  11:30 - 13:00
> Where: ProtoTekOKC 401 NW 10th St., OKC
> Speaker: *Sourav Pati* , Software Development Engineer , MBO Partners
> Topic:
>
> *Find Data in the Blink of an EyeElasticsearch*
> *Elasticsearch* – open source, distributed-full text search engine,built
> for speed. It offers solutions of scalability of big data search and it is
> accessible through API . In the recent time due to rapid growth of
> technologies, software development and its unprecedented utilization,
> search engine has become a paramount resource.
> During my presentation, we will see the basic concept of Elasticsearch,
> why should we care about it and how does it serve a mind-boggling
> performance. At the end we will see a few live examples of some the common
> use cases.
> We thank Techlahoma for generously providing the food and drink, and to
> ProtoTekOKC for providing the facility.
> See you there.
>

**Comment by rhoegg** [comment]
In our latest announcement, the thank you had links:

Please go to Meetup and sign up so we will have a count for the food. Meetup
> <http://meetu.ps/e/CjXlj/hQ4T0/d>We thank Techlahoma
> <http://techlahoma.org/> for generously providing the food and drink, and
> to StarSpace46  <http://www.starspace46.com/>for providing the facility.

**Comment by seejessicacode** [comment]
Thanks I will have @kacollins get on that.

As for the PR Integration that is above my and @kacollins head. You're welcome to make it and show us, but we've put enough work and time into this GH issue alone considering the lack of feedback, OKC JUG meetups getting cancelled or not scheduled early enough, etc etc.

**Comment by rhoegg** [comment]
I never assumed you would spend a lot of time on it until we spent the time
to answer your questions. Our bunch is usually willing to help out with
things, especially when they're things we're asking for.

For the PR integration: sure, I'd be willing to try to figure it out. Seems
like there's good reason to find a way to enable other volunteers to pitch
in.

I am not familiar with Zapier yet, so I don't know how PR's would work.
From your reply, I assume the source code for the integrations isn't in
github?

Also, would that idea be a separate github issue?

**Comment by seejessicacode** [comment]
> I never assumed you would spend a lot of time on it until we spent the time
to answer your questions. Our bunch is usually willing to help out with
things, especially when they're things we're asking for.

Actions speak louder than words, and I'm hearing the opposite message from you:
Jan 17, 2017 (same day that this GH issue was posted and 2 months, 24 days before your first response)
![image](https://cloud.githubusercontent.com/assets/943398/24909630/4b5b1bc0-1e8a-11e7-8ae8-effd928ffa69.png)

Feb 3, 2017 (2 months, 7 days before your first response)
![image](https://cloud.githubusercontent.com/assets/943398/24909588/1cd8c914-1e8a-11e7-862b-7f2c1f93316a.png)

**Comment by kacollins** [comment]
@rhoegg, I'm not familiar with Zapier yet either, but it looks very similar to IFTTT. It's more like a flow of steps than code.  GitHub is an option for integrating with Zapier (like Meetup is), but I'm not sure whether it could be used in the way that you're thinking. I will have to learn more about it.

Would the following template work? Any other information that you want in the main body of the email (such as information about the speaker) would need to be in the Meetup event description.

Email Subject:
`[OKCJUG] <Event Date> Meeting: <Event Name>`

Email Body:
```
When: <Event Date> <Event Start Time> - <Event End Time>
Where: <Venue Name> <Venue Address> <Venue City>, <Venue State>

<Event Description>

Please go to Meetup and sign up so we will have a count for the food. <Link to Event>
```

**Comment by kacollins** [comment]
I sent an email to jug-owner@lists.okcjug.org to request access for techlahoma@gmail.com to post to the OKC JUG mailing list.

Here's what the template looks like using the sample Meetup data in Zapier:

![image](https://cloud.githubusercontent.com/assets/15042297/25013419/158f8052-2039-11e7-91b2-15fab8db7059.png)

**Comment by rhoegg** [comment]
I just subscribed to the JUG mailing list for techlahoma@gmail.com using this
form <http://lists.okcjug.org/listinfo.cgi/jug-okcjug.org>. The request
will need to be confirmed before it will work.

On Thu, Apr 13, 2017 at 11:07 AM, Kimberly Collins <notifications@github.com

**Comment by kacollins** [comment]
Thanks! I didn't realize that needed to be done. I don't have access to techlahoma@gmail.com, but I will ask for it or ask for someone who does to confirm the request.

**Comment by kacollins** [comment]
The request has been confirmed, so Zapier should send the email on Friday, May 5 (if the meetup event is created before then).

**Comment by kacollins** [comment]
I believe that this worked correctly except that the link to the meetup event was missing. I'll try to figure out what happened with that, and then consider this done pending further feedback.

![image](https://cloud.githubusercontent.com/assets/15042297/25757397/e9fbb89e-318f-11e7-85cd-27c94302b995.png)

**Comment by kacollins** [comment]
I believe that this is working correctly, and I have not received any other feedback on it.
