### ISSUE TITLE
Create LinkedIn post to a group for meeting announcements

### ISSUE THREAD

**Issue by rhoegg** [techlahoma/user-groups#110]
It would be a good idea for some groups to have meeting announcements create posts in a LinkedIn group. OKCJUG would like this.

**Comment by seejessicacode** [comment]
I will first need access to write to their LinkedIn group. Is there an OKC JUG account or does Techlahoma need a LinkedIn account with access to the group?

If passwords need to be shared, please share via LastPass to info@techlahoma.org. Anything shared with my email will probably just die with me.

**Comment by seejessicacode** [comment]
I'm having @kacollins take over OKC JUG feature requests.

**Comment by rhoegg** [comment]
Thanks Kimberly!

**Comment by kacollins** [comment]
@rhoegg, I can't find the OKC JUG group on LinkedIn. Can you please give me a link to it?

**Comment by kacollins** [comment]
Here's the OKC Java Users Group on LinkedIn: https://www.linkedin.com/groups/115850

What account should create the posts?

**Comment by rhoegg** [comment]
Good question. I believe right now they should come from Jason Lee (the
current president) rather than an automated account.  Then when the
president changes, use the new person's account

On Wed, Aug 23, 2017 at 11:26 AM, Kimberly Collins <notifications@github.com

**Comment by kacollins** [comment]
I discussed this with @afbarbaro, the new head organizer of OKC JUG. He is willing to post to the group manually each month. I'm not sure that I would have been able to automate this anyway.
