### ISSUE TITLE
Request reimbursement for food and drink for OKC JUG event | 2018-09-11

### ISSUE THREAD

**Issue by jasondlee** [techlahoma/user-groups#1121]
What: Oracle Turns Java Up to 11
When: 09/11/2018 11:30 am
Where: 912 North Classen Blvd

Check meetup for RSVP count: https://www.meetup.com/okcjug/events/254367405/

To request reimbursement, please complete the following steps:
- [x] Post picture of receipt(s) in this thread
- [x] Post photo(s) of the meetup in action on your meetup event
- [x] Submit [request for reimbursement](https://github.com/techlahoma/user-groups/wiki/Requesting-Reimbursement) from the Techlahoma Foundation on https://venmo.com within 1 month of the event

Any questions about reimbursement may be referred to the board treasurer.

cc  @jasondlee, @drodmaster

**Comment by jasondlee** [comment]
[OKC JUG September Pizza Receipt.pdf](https://github.com/techlahoma/user-groups/files/2372584/OKC.JUG.September.Pizza.Receipt.pdf)

**Comment by kacollins** [comment]
It looks like this has been reimbursed.
