### ISSUE TITLE
Request reimbursement for food for OKCRB 2018-11-08

### ISSUE THREAD

**Issue by johnmosesman** [techlahoma/user-groups#1198]
What: OKCRB - A Programmer Has No Name
When: 11/08/2018 11:30 am
Where: Clevyr Labs

Check meetup for RSVP count: https://www.meetup.com/DevopsOKC/events/256209841/

To request reimbursement, please complete the following steps:

  Post picture of receipt(s) in this thread
  Post photo(s) of the meetup in action on your meetup event
  Submit request for reimbursement from the Techlahoma Foundation on https://venmo.com within 1 month of the event
Any questions about reimbursement may be referred to the board treasurer.

**Comment by johnmosesman** [comment]
Didn't find an automated issue made for this one.

RSVPs: 27 https://www.meetup.com/OKC-Ruby/events/255619218/
Attendance: 23
Food total: $97.75
Where: Clevyr Labs
Venmo request sent.

Thank you!

![img_4652](https://user-images.githubusercontent.com/3760568/48225714-337e9000-e363-11e8-9bf5-61d728c779e8.JPG)

![img_4656](https://user-images.githubusercontent.com/3760568/48225645-ffa36a80-e362-11e8-9c2d-d8ae04aaf78b.JPG)

**Comment by johnmosesman** [comment]
@jsonthebson

**Comment by kacollins** [comment]
Thanks for the heads up. It looks like we have a bug in the logic for meetups that aren't at the usual location.

**Comment by johnmosesman** [comment]
Ah that would make sense!

**Comment by jsonthebson** [comment]
Paid. Thanks so much!
