### ISSUE TITLE
Book StarSpace46 for Code for OKC | 02/27/2017 6:00 pm

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#121]
What: February Hack Night
When: 02/27/2017 6:00 pm
Where: StarSpace46

Check meetup for RSVP count: https://www.meetup.com/Code-for-OKC/events/237156253/

**Comment by seejessicacode** [comment]
@mkchandler @jagthedrummer @cahiller I heard your crew out grew the holodeck last night, so I've booked the event space this time. Thanks for coding for OKC!
![image](https://cloud.githubusercontent.com/assets/943398/22248533/99a10a32-e204-11e6-96a8-522145012cf7.png)

**Comment by mkchandler** [comment]
@seejessicacode yep, we did! Thanks!
