### ISSUE TITLE
Automate SS46 Bookings in cobot?

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/user-groups#122]
I noticed SS46 is using cobot for calendar + events booking? At 36°N I'm pretty sure we've been able to automatically book recurring events for Tulsa Web Devs, TulsaJS, Tulsa Data Science, etc. Is that possible for SS46 too?

**Comment by seejessicacode** [comment]
Not through Zapier.

**Comment by groovecoder** [comment]
Their meetups aren't on the same day each month?

**Comment by seejessicacode** [comment]
Ideally yes, but meetups can reschedule or cancel due to holidays/weather/lack of speaker/life etc.

**Comment by seejessicacode** [comment]
If you're wondering about just booking the meetings manually, I already did that for the rest of 2017. It had to be done by hand because there was no "recurring event" option for SS46's cobot and there's not an automation flow available to schedule a cobot without human intervention, not through Zapier and Meetup.

**Comment by rhoegg** [comment]
Cobot has an API, and I've got some experience with it. What's 36N doing?
Where would I need to plug in to extend Techlahoma Zapier to use it?

**Comment by seejessicacode** [comment]
First I need to understand what this automation will do.
Objective: Reserve SS46 at least 2 months in advance
Things to account for:
- group size (when Techlahoma starts paying rent, venue cost will be a concern)
- how long to reserve (again, when Techlahoma starts paying rent, hours will be a concern)
- do they need streaming
- need user group name and url to specific Meetup event (per request of SS46 staff for advertising)

My main concern is maintaining another tool that myself and other volunteers will still have to babysit.

As far as plugging into Zapier, there's a JavaScript/Python code channel that can be run like a chron job. https://zapier.com/help/code/

**Comment by the-simian** [comment]
One thing to note is that we're looking into a better 2-way bound calendar with meetup, which should also help some with updates/etc. If it works the way we expect, it can be reliably hooked into for scripts. Since that's pretty important its something we're working on sooner rather than later.

Just mentioning that to make it clear what the short term priorities are

**Comment by seejessicacode** [comment]
2-way bound calendar with meetup would be AWESOME!!!

**Comment by seejessicacode** [comment]
I still wonder about hiccups with events scheduled throughout the year to accommodate SS46's request for 2+ months notice... but as long we can pair the cobot reservation with the right meetup event as it is created and update that reservation accordingly, then this should be good.

**Comment by rhoegg** [comment]
I'd think maintaining an accurate three months of bookings would be a good
goal, and not too tricky.

**Comment by seejessicacode** [comment]
My experience is getting 15+ UG leaders to coordinate is a beast. I'm still getting initial responses from emails and DMs I sent last October.

**Comment by rhoegg** [comment]
Lol! Of course, I'm thinking for this issue, just keeping ss46 in sync with
whatever is in meetup for a 3 month horizon is good enough.

**Comment by the-simian** [comment]
Things have gotten better even having meetup being the ug leader's point of entry, but it could be better still I think. 3 months isn't that unreasonable of a request at all IMO. I think we can do this.

**Comment by kacollins** [comment]
StarSpace46 doesn't use Cobot anymore.
