### ISSUE TITLE
Book 36°N for Tulsa Game Developers | 2017-02-16

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#125]
What: February Meeting: Happy Birthday TGD! Global Game Jam Tulsa recap
When: 02/16/2017 7:00 pm
Where: 36 Degrees North

Check meetup for RSVP count: https://www.meetup.com/Tulsa-Game-Developers/events/237193826/

cc @dcurzon

**Comment by groovecoder** [comment]
TGD is auto-booked in 36°N Calendar every month.

http://www.36degreesnorth.co/calendar/

**Comment by seejessicacode** [comment]
Cool, I will set the automation for this group to announcements only.
