### ISSUE TITLE
New User Group Submission: TLL, Tulsa Lambda Lunch

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#127]
**Agree to CoC:** Yes
**Proposed group name:** TLL, Tulsa Lambda Lunch
**City:** Tulsa
**Purpose:** Functional Programming Principles, Languages, and Techniques for beginners to experts
**Twitter:** 
**Website:** 
**Would like help with:** General Mentorship, Venue Assistance, Event Insurance, Social Media / Announcement, Connecting to the greater OK communtiy

Submitted by Darren Gibson on 01/26/2017 19:32:22

**Comment by seejessicacode** [comment]
Here is their meetup website: https://www.meetup.com/Tulsa-Lambda-Lunch/

**Comment by seejessicacode** [comment]
@zarthross The board will be discussing on boarding more user groups soon.

Can you list who the organizer and co-organizers will be? It's important to Techlahoma that user groups have at least 2 leaders (extra points for 1 or 2 volunteers) to ensure the stability of the user group.

It is also my understanding that you'll be meeting the last Tuesday of each month at the same time as OKC FP, with the possibility of just taking turns streaming each other's talks. Is this correct? This won't be possible until 36°N can stream (which is in the works, just not sure when it'll be ready).

Will you need assistance with funding for food or have you found a sponsor to provide that?

**Comment by zarthross** [comment]
> Can you list who the organizer and co-organizers will be? It's important to Techlahoma that user groups have at least 2 leaders (extra points for 1 or 2 volunteers) to ensure the stability of the user group.

Organizer: Darren Gibson
Co-organizer: Greg Tatum 
I'll ask around for an additional volunteer or two, thats a good idea.

> It is also my understanding that you'll be meeting the last Tuesday of each month at the same time as OKC FP, with the possibility of just taking turns streaming each other's talks. Is this correct? 

Yes, that is correct.  We do not plan on doing the steaming initially but that is a long term goal.

 > Will you need assistance with funding for food or have you found a sponsor to provide that?

I have a verbal agreement with the food sponsor of Tulsa Java that they would also sponsor TLL.  I've emailed them again with an update about TLL's progress and asked to confirm they would still be sponsoring food.  I'll post an update here when I've confirmed this.

I believe the only thing we will need funding for is the cost of the meetup.com group.  For now I've paid for it out of pocket so the ball could get rolling.

**Comment by seejessicacode** [comment]
The board took a vote last night and we're excited to include TLL in our mission! Keep an eye out for an official email from an @techlahoma.org address. I wouldn't expect it any sooner than this weekend.

**Comment by seejessicacode** [comment]
- [ ] automate announcements
- [ ] make Techlahoma organizer of Meetup group
- [ ] add to techlahoma usergroups website 
- [ ] make GH issue label for group
