### ISSUE TITLE
Book SS46 for OKCSQL 2-20-2017 6-8pm

### ISSUE THREAD

**Issue by sqlcenturion** [techlahoma/user-groups#128]
https://www.meetup.com/OKCSQL/events/236206718/

**Comment by seejessicacode** [comment]
@sqlcenturion We're still waiting on OKC SQL to make Techlahoma organizer of their meetup. OKC SQL is not officially a Techlahoma user group until this step is complete.

https://www.meetup.com/OKCSQL

**Comment by seejessicacode** [comment]
I've now made two attempts to contact Allen myself. Both attempts through Meetup.com

January 9th, 2017 1:13 pm
>People are confused because OKC SQL is meeting the 16th instead of tonight, yet the Meetup isn't updated.
>
>I'm going to update the Meetup and send a message to all members that there's not meeting tonight.
>
>Since Matt Brimer and Bill Barnes have joined Techlahoma on OKC SQL's behalf. We need to take over as organizer and make them co-organizers. Could you step down as organizer and promote Techlahoma to take over?
>Instructions at: https://github.com/techlahoma/user-groups/wiki/Meetup#2-make-techlahoma-the-organizer-and-the-user-group-leader-co-organizer
>
>Thank you,
>
>Jessica Campbell
>User Group Committee Member
>Techlahoma
>
January 27, 2017 12:48 pm
>We haven't heard from you and Matt Brimer reports that he has asked you to transfer organizer role of OKCSQL to us.
>
>Latest communication with Matt Brimer at https://github.com/techlahoma/user-groups/issues/128
>
>Please refer to earlier message for instructions on how to transfer organizer role to us.
>
>If you have any questions or concerns, please feel free to tell us.
>
>Jessica Campbell
>User Group Committee member
>Techlahoma

**Comment by seejessicacode** [comment]
![image](https://cloud.githubusercontent.com/assets/943398/22437843/3d50b79c-e6ef-11e6-8589-ce2123ee3735.png)
