### ISSUE TITLE
Existing User Group: OKC Raspberry Pi

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/user-groups#13]
**Name:** Kimberly Collins

**Email Address:** [removed for privacy]

**Do you agree to follow the Techlahoma Code of Conduct & Anti-Harassment Policy?:** Yes

**Group Name:** OKC Raspberry Pi

**Current Organizers & Volunteers:** Verbus Counts and Kimberly Collins

**Meeting Date Information:** Second Saturday

**Current Meeting Location:** Edmond Bahá'í Center

**Average Attendes:** 5-10

**Average Meeting Cost:** $0

**Who sponsors your group?:** Group has no sponsors

**Group Website:** www.meetup.com/OKC-Raspberry-Pi-Meetup/

**Group Twitter:** okcrpi

**What would you like help with:** General Mentorship, Venue Assistance, Finding Event Speakers, Funding for Food & Drink, Social Media / Announcement, Connecting to the greater OK communtiy

_Submitted on 07/29/2016 at 7:26 am_

**Comment by amandaharlin** [comment]
We need a group email address for these UGs, not just personal organizer
emails. What so you think about group techlahoma emails? E.g.
BUG@techlahoma.org, raspberrypi@techlahoma.org

**Comment by seejessicacode** [comment]
I'm down with it, but there is two hiccups with this setup that I've already run into with OKCFP:

1. Some folks have blocked invitations to google groups
2. Checking the google group email is either too easily forgotten or just out of the way.

We should be able to remedy the second point with email forwarding to personal emails. Only possible concern is that if leadership replies to an email, it'll be from their personal email. I find this hard to care about though. If anyone wants to keep their personal email private, they'll need to use the google group email.

**Comment by energydev** [comment]
Awhile back, we had OKCDG e-mail addresses forwarding to our personal e-mail addresses. This ended up causing the spam filters for at least one major provider to essentially declare anything from our domain as spam.

**Comment by energydev** [comment]
For OKCSQL, I believe we were able to hookup our personal e-mail providers to also pull-in e-mails from our okcql.org e-mail addresses. I know in my case, I could receive and send e-mail from the okcsql.org e-mail address that I had, even though I was logged into my personal e-mail provider. You might follow-up with @datachomp about this, as I believe he's the one that initially handled setting up the okcsql.org e-mail accounts.

**Comment by seejessicacode** [comment]
@energydev How does this concern OKC Raspberry Pi's user group application?

**Comment by amandaharlin** [comment]
Oh yeah, that's what happened. Anyway, I think what I meant to say was that if folks are trying to email groups we might need a group email available for the community (like how we have okcjs' email instead of people emailing jesse.) It's not a big deal anyhow.

**Comment by seejessicacode** [comment]
Approved if OKC Raspberry Pi renames group to something less product specific! Will close issue after following up with UG leader(s).

https://github.com/techlahoma/board_meetings/blob/master/2016/12_december-minutes.md

**Comment by seejessicacode** [comment]
Approval email sent.

**Comment by seejessicacode** [comment]
- [ ] Add to http://www.techlahoma.org/usergroups/
- [ ] Add to https://www.meetup.com/pro/techlahoma/
- [ ] Set up automation for announcements and GH issues
