### ISSUE TITLE
Remove folder for OK PHP since it has been split into OKC PHP and Tulsa PHP

### ISSUE THREAD

**Issue by kacollins** [techlahoma/user-groups#133]
https://github.com/techlahoma/user-groups/tree/master/OK-PHP

https://github.com/techlahoma/user-groups/tree/master/OKC-PHP
https://github.com/techlahoma/user-groups/tree/master/Tulsa-PHP

**Comment by the-simian** [comment]
Oh yeah you're right we need to do that

**Comment by vlucas** [comment]
Good call. 👍
