### ISSUE TITLE
Request reimbursement for food and drink for Free Code Camp Norman | 2019-01-29

### ISSUE THREAD

**Issue by chris-tse** [techlahoma/user-groups#1337]
What: A Day in the Life of a Developer with Brian Chirgwin
When: 01/29/2019
Where: 201 David L Boren Blvd, Norman, OK

Check meetup for RSVP count: https://www.meetup.com/FreeCodeCamp-Norman/events/258276481/

To request reimbursement, please complete the following steps:

- [x] Post picture of receipt(s) in this thread
- [x] Post photo(s) of the meetup in action on your meetup event
- [x] Submit request for reimbursement from the Techlahoma Foundation on https://venmo.com within 1 month of the event

Any questions about reimbursement may be referred to the board treasurer.

**Comment by chris-tse** [comment]
![20190129_180042](https://user-images.githubusercontent.com/250450/51990640-17c0ec80-246f-11e9-8af0-b610e0ec417d.jpg)

**Comment by jsonthebson** [comment]
Paid, thank you!
