### ISSUE TITLE
Reqquest reimbersement for food and drink for ProductTank OKC meetup | 2019-02-05

### ISSUE THREAD

**Issue by josephscottbond** [techlahoma/user-groups#1346]
What: Dave Luna- The relationship between product and design
When:02/05/2019 11:30 am
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count:https://www.meetup.com/ProductTank-OKC/events/258343516/

To request reimbursement, please complete the following steps:

* [x]  Post picture of receipt(s) in this thread
* [x]  Post photo(s) of the meetup in action on your meetup event
* [x]  Submit [request for reimbursement](https://github.com/techlahoma/user-groups/wiki/Requesting-Reimbursement) from the Techlahoma Foundation on https://venmo.com within 1 month of the event

Any questions about reimbursement may be referred to the board treasurer.

cc @nexocentric @vianka-a

**Comment by josephscottbond** [comment]
![img_4457](https://user-images.githubusercontent.com/9885658/52386416-a8896080-2a4b-11e9-9f2d-e77e6cea2e70.JPG)
![cainesreceipt](https://user-images.githubusercontent.com/9885658/52386417-aaebba80-2a4b-11e9-88d9-deade499dea4.JPG)

**Comment by josephscottbond** [comment]
![cainesreceipt](https://user-images.githubusercontent.com/9885658/52386976-facb8100-2a4d-11e9-949a-2b9350d33fe2.jpg)

**Comment by jsonthebson** [comment]
Hi Joe, the receipt doesn't look like it was properly uploaded. Can you try again?

**Comment by jsonthebson** [comment]
@carmalou This one doesn't look like it was auto-generated. Please confirm they should be getting reimbursed.

**Comment by josephscottbond** [comment]
@jsonthebson 
I've been trying to drag/drop the image into the comments... Isn't seeming to work. 

Here's a link to it in my google drive: https://drive.google.com/file/d/18-B32UQue0Otv-DQIZP79kHO9k8pCC2d/view?usp=sharing

**Comment by jsonthebson** [comment]
That'll work. Thanks!
