### ISSUE TITLE
Book StarSpace46 for Big Data and Data Science in OKC | 2019-03-07

### ISSUE THREAD

**Issue by max522over** [techlahoma/user-groups#1404]
What: Got Milk? Modeling a Dairy Allergy: Oral Immunotherapy and the Immune Response
When: 03/07/2019 11:30 am
Where: StarSpace 46

Check meetup for RSVP count: https://www.meetup.com/Big-Data-in-Oklahoma-City/events/258171315/

cc  @max522over

**Comment by carmalou** [comment]
booked
