### ISSUE TITLE
Reschedule DevopsOKC March meeting for March 22.

### ISSUE THREAD

**Issue by claytonflesher** [techlahoma/user-groups#1405]
Generally, we hold the Devops meetup on the third Friday of the month, which would be March 15 this time.

Our March speaker asked if we could push it back a week this month. I spoke with Ava and Tommy at Starspace46 and confirmed that the event space was available at that time on that date, and reserved the room.

I also updated the rotating event on our Meetup page to reflect the different date.

This month it will be March 22 at 11:30 a.m. at Starspace46.

**Comment by carmalou** [comment]
this is fixed up. thanks @claytonflesher!
