### ISSUE TITLE
Arrange food, drink, and venue access for OKC Ruby event | 02/09/2017 11:30 am

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#142]
What: Best Practices for Building a JSON API with Rails 5
When: 02/09/2017 11:30 am
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/OKC-Ruby/events/237438818/

cc @jagthedrummer @datachomp @piisalie

**Comment by amandaharlin** [comment]
food is ordered and got a salad for paul.

**Comment by jagthedrummer** [comment]
Thanks, Amanda! We had about 22 people show up for the meeting. 4 pizzas was a good amount of food.
