### ISSUE TITLE
Book StarSpace46 for OKC Ruby | 02/09/2017 11:30 am

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#143]
What: Best Practices for Building a JSON API with Rails 5
When: 02/09/2017 11:30 am
Where: StarSpace 46

Check meetup for RSVP count: https://www.meetup.com/OKC-Ruby/events/237438818/

cc @jagthedrummer @datachomp @piisalie

**Comment by seejessicacode** [comment]
![snip20170205_3](https://cloud.githubusercontent.com/assets/943398/22631537/c127f1c2-ebd4-11e6-997a-2898d04d67bd.png)
