### ISSUE TITLE
Request Reimbursement for Food and Drink for ProductTank OKC meetup April 2, 2019

### ISSUE THREAD

**Issue by josephscottbond** [techlahoma/user-groups#1431]
What: ProductTank OKC Monthly Meetup
When: 04/2/2019 11:30 am
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/ProductTank-OKC/events/259959423/

To request reimbursement, please complete the following steps:

- [x]   Post picture of receipt(s) in this thread
- [x]  Post photo(s) of the meetup in action on your meetup event
- [x]  Submit request for reimbursement from the Techlahoma Foundation on https://venmo.com within 1 month of the event
Any questions about reimbursement may be referred to the board treasurer.

![IMG_0782](https://user-images.githubusercontent.com/9885658/55656810-e097f000-57bd-11e9-8d98-a36e0d8dcf43.JPG)

**Comment by kendallcorner** [comment]
Paid, thanks!
