### ISSUE TITLE
Update Oklahoma City Open Source Hardware Group: 2019-5-11

### ISSUE THREAD

**Issue by LokiMetaSmith** [techlahoma/user-groups#1445]
OKC-OSH usually meets at Starspace. We're moving venues for hands on projects and tool access. 

What: 3D Printers Workshop
When: 5/11/2019 2:00 pm
Where: Project 3810

Check meetup for RSVP count: https://www.meetup.com/OKC-OSH/

cc @jed, @LokiMetaSmith, @scifiaholic

**Comment by LokiMetaSmith** [comment]
So, The talk topic changed to 3D Modelling the World Around You and the attendance is up to 17 people and doesn't make use of 3D printers. 
The presenter also wants to stream the talk, which isn't setup yet. 

Would it be possible to switch back to starspace for this event?

**Comment by carmalou** [comment]
booked at starspace. please be sure to let project 3810 know.
