### ISSUE TITLE
Arrange food, drink, and venue access for OKC.js event | 02/21/2017 11:30 am

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#145]
What: WebAssembly
When: 02/21/2017 11:30 am
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/OKC-js/events/237462189/

cc @the-simian @amandaharlin @vlucas

**Comment by amandaharlin** [comment]
cane's is ordered. i'll post a receipt tomorrow

**Comment by seejessicacode** [comment]
We had 72 people (WOWEE!!) Food was G.O.N.E. but I heard no complaints. Bread and sauce were the first to go though, so I bet some folks were bummed about that. I was... but that was when I was going for seconds so it's not like I didn't have any.

![20170221_104839](https://cloud.githubusercontent.com/assets/943398/23179979/6fbdd726-f835-11e6-83cd-c19fc8af139f.jpg)

![20170221_103852](https://cloud.githubusercontent.com/assets/943398/23179996/7bd6ffce-f835-11e6-8710-2e0ea082b318.jpg)

![image uploaded from ios](https://cloud.githubusercontent.com/assets/943398/23179965/6502df20-f835-11e6-89a6-d64031e294c6.jpg)

**Comment by seejessicacode** [comment]
Group photo! (stolen from https://twitter.com/BrettDOkc/status/834104487677743110)
![c5nvm6dukaazmne](https://cloud.githubusercontent.com/assets/943398/23180173/1ed1701a-f836-11e6-8aeb-416196d5c1f7.jpg)
