### ISSUE TITLE
Book StarSpace46 for OKC.js | 02/21/2017 11:30 am

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#146]
What: WebAssembly
When: 02/21/2017 11:30 am
Where: StarSpace46

Check meetup for RSVP count: https://www.meetup.com/OKC-js/events/237462189/

cc @the-simian @amandaharlin @vlucas

**Comment by seejessicacode** [comment]
![snip20170205_1](https://cloud.githubusercontent.com/assets/943398/22631497/28990b76-ebd4-11e6-8e79-aa77c178ec72.png)
