### ISSUE TITLE
SheCodes reimbursement 04-28-19

### ISSUE THREAD

**Issue by carmalou** [techlahoma/user-groups#1461]
the automation didn't make the issue, so this is our stand-in issue.

**Comment by CaitlinS9** [comment]
![image](https://user-images.githubusercontent.com/11357191/56869502-392a6980-69c7-11e9-8fc9-6307881982d5.png)
![image](https://user-images.githubusercontent.com/11357191/56869508-4f382a00-69c7-11e9-9930-e925d41e92ea.png)

**Comment by CaitlinS9** [comment]
03.24.19
![image](https://user-images.githubusercontent.com/11357191/56869525-7262d980-69c7-11e9-858a-e8df06660493.png)

**Comment by kendallcorner** [comment]
Paid, thanks!!
