### ISSUE TITLE
Move StarSpace46 booking for OKC-FP | 2019-04-29

### ISSUE THREAD

**Issue by jordan-parmer** [techlahoma/user-groups#1463]
This month's OKC-FP is being moved from Tuesday, April 30th to Friday, May 3rd. We'll be using StarSpace46 and streaming on Twitch.

**Comment by jordan-parmer** [comment]
May 3rd, 11:30AM - 12:30 PM
@alexadriaanse will be handling the Twitch live stream.

**Comment by kacollins** [comment]
I went ahead and updated the announcement calendar.

**Comment by carmalou** [comment]
booked
