### ISSUE TITLE
Request Reimbursement for food/drink for ProductTank OKC

### ISSUE THREAD

**Issue by josephscottbond** [techlahoma/user-groups#1486]
What: ProductTank OKC
When: 05/7/2019 11:30 AM
Where: 1141 W. Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/ProductTank-OKC/events/260925148/

To request reimbursement, please complete the following steps:

- [X ]   Post picture of receipt(s) in this thread
- [X ]   Post photo(s) of the meetup in action on your meetup event
- [X ]   Submit request for reimbursement from the Techlahoma Foundation on https://venmo.com within 1 month of the event

Any questions about reimbursement may be referred to the board treasurer.

![IMG_0051](https://user-images.githubusercontent.com/9885658/57872447-520d8a00-77d1-11e9-8d76-3006ee7120fb.JPG)

**Comment by jsonthebson** [comment]
Paid, thanks!
