### ISSUE TITLE
Arrange food for OKC Python

### ISSUE THREAD

**Issue by mmattice** [techlahoma/user-groups#150]
What: OKC Python
When: 02/08/2017 11:30 AM
Where: 1141 W Sheridan Ave, Oklahoma City

https://www.meetup.com/Oklahoma-City-Python-Users-Group/events/236717796/

Count is presently 22

**Comment by seejessicacode** [comment]
Thanks @mmattice! With the chron job I've set up, I'm hoping future issues like this will be generated two weeks in advance. We'll see on Feb 22.
