### ISSUE TITLE
Define a reimbursement process for UG leaders

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/user-groups#151]
To eliminate the overhead and stress of UG committee ordering food for every meetup, we should define a process for UG leaders to be reimbursed for their meetup food costs.

Requirements:
1. UG leaders buy their own food for their meetups
2. UG leaders upload a copy of their receipts
3. UG committee approves all reimbursements
4. No physical checks

## Option 1: Provide the UG leaders gift cards
This will set a spending limit and we can limit them to one gift card a quarter.

The challenges with this approach would be:
1) getting the gift card to the UG leader (does Domino's offer email gift certificates?)
2) choosing a spending limit for any UGs that fluctuate in attendance
3) requiring receipts from UG leaders even though the we already provided the gift card
4) not restricting UGs to a single restaurant chain
5) do gift cards cover tip?

For 4), there are prepaid credit cards, but the service charge is like $3 a transaction so I don't recommend it :confused:

## Option 2: cash.me/$techlahoma
UG leaders will sign into cash.me, visit cash.me/$techlahoma, and request reimbursement for the amount they spent on their meetup.

**Comment by groovecoder** [comment]
## Option 3: Expensify
It's expensive, but has worked well for Code for America & brigades.

**Comment by blazedd** [comment]
## Option 4: privacy.com

This gives us the same flexibility of option #1, but allows us to automatically define monthly limit. They issue proxy credit cards which are attached to a specific bank account or credit card. You can then set limits or even disposable cards which are all defined by the software. This eliminates vender lock-in and extra work by staff to manage gift cards. The only question is pricing as they are in their pre-revenue stage and are not charging anything.

I use it personally and really like it.

**Comment by seejessicacode** [comment]
Regarding option 2: cash.me/$techlahoma, we would need to claim the transaction as "personal" otherwise the UG leaders requesting reimbursement will be charged 2.75% of the requested amount.
![image](https://cloud.githubusercontent.com/assets/943398/22760796/ad4974d2-ee1d-11e6-802e-13ebb3c9a052.png)

**Comment by groovecoder** [comment]
@blazedd - are the privacy.com physical cards UG leaders could use in-store? Or are they 100% virtual to be used online?

**Comment by groovecoder** [comment]
@seejessicacode in fact, they (or we, or both) might be charged a transaction fee anyway when they go to withdraw the $$ from cash.me.

I'm having @jdungan try it out for a Tulsa Web Devs meetup he needs to expense and get reimbursement. We'll see what all fees are involved and report back here.

**Comment by blazedd** [comment]
@groovecoder strictly virtual cards. I know they are limiting, but for a lot of situations it'll work.

Slight tangent, but we could also start talking to managers or owners about opening expense accounts. A lot of non-profits do this and pay a monthly invoice, rather than at the order time. I've been meaning to handle this for Starspace for too long.

**Comment by groovecoder** [comment]
Whoa, I just discovered ...

## Option 5: Xero Touch

It's already integrated into our Xero accounting software, and there's a free mobile app for UG leaders to use:

https://www.youtube.com/watch?v=B7XnC2H8078

I just did it for TWD receipts I need to expense from last night (used personal card b/c I left Techlahoma card at home). Easy paint-by-pictures process!!

### Step 1
![xero-1](https://cloud.githubusercontent.com/assets/71928/22767196/745b033a-ee3f-11e6-8b7a-ae737fb14468.png)

### Step 2
![xero-2](https://cloud.githubusercontent.com/assets/71928/22767205/7ba0355c-ee3f-11e6-8f82-fd6f4529ea5f.png)

### Step 3
![xero-3](https://cloud.githubusercontent.com/assets/71928/22767216/9272aa12-ee3f-11e6-974f-fdf48089f003.png)

### Step 4
![xero-4](https://cloud.githubusercontent.com/assets/71928/22767230/a1eeaebe-ee3f-11e6-9bf5-b96bb93ac50f.png)

### Step 5
![xero-5](https://cloud.githubusercontent.com/assets/71928/22767234/a63c26cc-ee3f-11e6-81a2-0c1d4b72ac26.png)

### Step 6
![xero-6](https://cloud.githubusercontent.com/assets/71928/22767237/ae55f036-ee3f-11e6-973d-3c140570f597.png)


On the approval side, there's an easy approval dashboard in Xero, but I can't tell if it can send payments automatically too? @amandaharlin ?

**Comment by seejessicacode** [comment]
A big concern brought up in the past is that some UG leaders need us to pay up front because they can't afford to wait for a reimbursement.

**Comment by the-simian** [comment]
that xero touch is really nice

**Comment by the-simian** [comment]
man i need to be using xero touch for simiancraft too

**Comment by seejessicacode** [comment]
Who is on the finance committee? This will be a big deal to a lot of our groups so it would help the user-group committee to know who to direct the UG leaders too for their expense questions/concerns.

I would prefer to track receipts and event headcount and then set spending limits for our UG leaders, but those metrics will still require peer review and not really lightening the load. However, I consider it the finance committee's decision on how to exercise fiscal responsibility and visibility.

**Comment by groovecoder** [comment]
The reimbursement process should be optional - let's use it when it works for UG leaders AND UG committee.

Whatever process we pick, let's gradually/manually implement it while we learn the average cost & headcount for each UG. Guidelines & finance committee approval will be easier on all of us than setting hard limits from the very start.

**Comment by seejessicacode** [comment]
Closing since task is broad and last update to discussion was over a month ago.
