### ISSUE TITLE
User Group Calendar does not appear to be maintained

### ISSUE THREAD

**Issue by kacollins** [techlahoma/user-groups#154]
http://www.techlahoma.org/calendar

I didn't see any links to this page on the Techlahoma website, but it still comes up in search results. It might be better to take it down or have it point to the meetup.com list instead.

http://www.techlahoma.org/test-calendar/ comes up when Googling "Techlahoma calendar" also.

**Comment by amandaharlin** [comment]
ok, i just disabled the page so it shouldn't be accessible anymore.

**Comment by the-simian** [comment]
we're gonna replace this calendar with another when we wrap up our receipt generator project
