### ISSUE TITLE
Existing User Group Submission: Tulsa Agile Practitioners

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#156]
**Agree to CoC:** Yes
**Group name:** Tulsa Agile Practitioners
**Purpose:** 
**Current location:** 36° North 
**Current meeting date and time:** Second Thursday of every month. Also, second Tuesday of every month
**Leadership:** Jason Knight
Floyd May
Michael Lundsford
Mike Maddox
**Avg. # of attendees:** 15 - 25
**Avg. cost per meeting:** $200
**Who sponsors your group?:** Recruiters
**Twitter:** agile_tulsa
**Website:** https://www.meetup.com/TulsaAgilePractitioners/
**Would like help with:** General Mentorship, Social Media / Announcement, Connecting to the greater OK communtiy

Submitted by Jason Knight on 02/15/2017 22:45:52

**Comment by seejessicacode** [comment]
@jugisahunk I'm reviewing the list of items TAP would like help with. Is food already covered or does TAP not need it?

TAP meets 2x a month, with an average cost of $200 per meeting. So TAP would cost an average of $400. Is this covered by other sponsors?

**Comment by jugisahunk** [comment]
No, total cost per month is only about $200 since only one of our meetings needs sponsored food. It is covered by my partners at TekSystems.

**Comment by jugisahunk** [comment]
We're mainly interested in getting help sponsoring speakers and in promoting our activities towards the benefit of software delivery in Tulsa. We're a relatively small group ~180 members. Our network is homegrown an has limited visibility and discoverability throughout the city and State therefore, our mission to improve the delivery of software by supporting and equipping those who are doing it is limited. We would dearly love to partner with you all to attract, fund and publicize our efforts to bring expertise into the state from all around the country.

We have a line on funding from the Agile Alliance. They have reimbursed one speaker's travel so far and we fully intend to push them to the limit of their willingness to do so for future speakers :). Where they are unable or unwilling or unable to support our efforts and where they are unable to help us publicize opportunities for learning, we would look to Techlahoma.

Does that help?

**Comment by seejessicacode** [comment]
That helps a lot! Thanks!

**Comment by groovecoder** [comment]
@jugisahunk - when you say "sponsoring speakers" do you mean paying for visiting speakers? And/or finding speakers? For the latter, we started a [SPEAKERS-AND-TOPICS](https://github.com/techlahoma/user-groups/blob/master/SPEAKERS-AND-TOPICS.md) here in this repo that you can go thru to find a (free and local!) speaker.

**Comment by jugisahunk** [comment]
Sorry missed replying to this. **We wouldn't not additional funding as a condition for joining**. If funding is available for speakers that would be awesome. We are looking to expand the material and exercises available to the group by partnering with folks interested in improving software development and delivery in Tulsa.

Getting more exposure when we do have out of town speakers and and butts in seats on the actual day is of more immediate concern for us. Additionally, Techlahoma would be an outlet for several TAP members to gain experience presenting the material they've developed by presenting at TAP over the years.

So how about it. Do we get in? 
![image](https://media1.giphy.com/media/PCkcS10XqAoBa/giphy.gif)

**Comment by seejessicacode** [comment]
Thanks for answering my questions! I wish I could give you an answer right now as your application is very promising!! This is up to the board however and I know their hands are full finding sponsors for 8 groups we on-boarded this year, so I am not sure when they'll be ready to vote.

Don't worry I'll keep nagging ;)

In the meantime, please feel free to join our slack community if you haven't already. You can even have a channel for your UG is you'd like. We're fairly casual there, the CoC remains and we discourage use of @channel usage in public channels or job postings in general channels like #tech or #random but that's roughly it. You can msg me or other board members with any questions.

http://slack.techlahoma.org/

**Comment by jugisahunk** [comment]
What does sponsorship mean? We have funding already for what we need to
operate. Additionally, I organize it so additional logistic support would
be nice but not required.

**Comment by seejessicacode** [comment]
Ah, good point.

We do require each usergroup have a Meetup.com group that our Techlahoma account be assigned the role "organizer" for. It is only then that we can include a UG in the following page: https://www.meetup.com/pro/Techlahoma/
This costs us $15 per UG per month.

The user group committee will also set up and maintain some automations that will help schedule announcements for your UG on Techlahoma's social media and any GH issues for routine meeting tasks like reserving space or ordering food, which in isn't necessary in Tulsa Agile Practitioners' case. These automations are usually a one time setup but it's not unusual for a UG to have a special request and we try to accommodate.

So the financial sponsorship would just be Meetup.com.

**Comment by jugisahunk** [comment]
Thank you for the clarification. That all sounds just fine :). 

I've been assuming the meetup.com/TulsaAgilePractitioners cost myself over the last 3 years. Do I understand correctly that Techlahoma would begin paying our meetup costs (logistically) as meetup organizer for TAP and we would pay Techlahoma $15 every month to cover the $180 yearly cost? I'd have no problem doing that since I'm already investing personally in the group year over year :).

**Comment by seejessicacode** [comment]
Techlahoma would be paying the Meetup fees, but you would not be paying Techlahoma any money.

The board meeting was last night and we took a vote and we're proud to include TAP in our community! Keep an eye on your inbox for some official email, but you probably won't get one until the weekend.

**Comment by jugisahunk** [comment]
w00t!!

**Comment by seejessicacode** [comment]
- [ ] automate announcements
- [ ] make Techlahoma organizer of Meetup group
- [ ] add to techlahoma usergroups website 
- [ ] make GH issue label for group

**Comment by seejessicacode** [comment]
@jugisahunk could you make Techlahoma organizer of this Meetup group? https://github.com/techlahoma/user-groups/wiki/Meetup#2-make-techlahoma-the-organizer-and-the-user-group-leader-co-organizer

**Comment by jugisahunk** [comment]
Will do :)

**Comment by jugisahunk** [comment]
Ok, I've stepped down and invited Techlahoma to be the new organizer.

**Comment by seejessicacode** [comment]
Thanks! I've accepted it on Techlahoma's behalf and bumped you to co-organizer.

**Comment by jugisahunk** [comment]
w00t!
