### ISSUE TITLE
Arrange food and drink for OKC SQL | 2017-02-20

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#157]
What: OKCSQL Monthly Meeting
When: 02/20/2017 6:00 pm
Where: 1141 W Sheridan, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/OKCSQL/events/236206718/

cc @sqlcenturion @DBAOnTheGo

**Comment by kacollins** [comment]
I was under the impression that a sponsor provided the food.

**Comment by sqlcenturion** [comment]
they do, I don't know where this came from

**Comment by seejessicacode** [comment]
Okay I'll remove this. Thanks!
