### ISSUE TITLE
Book 36°N for Code for Muskogee | 2019-09-21

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#1683]
What: National Civic Day of Hacking
When: 09/21/2019 10:00 am
Where: 36 Degrees North

Check meetup for RSVP count: https://www.meetup.com/Code-for-Muskogee/events/264750665/

cc @dcurzon, @sgelbart, @ezrinjaz

**Comment by groovecoder** [comment]
Covered by reservation by @chimchim237 .
