### ISSUE TITLE
Delivery food for January Tulsa Web Dev meeting 

### ISSUE THREAD

**Issue by jdungan** [techlahoma/user-groups#169]

**Comment by jdungan** [comment]
Here are the receipts for the January Meeting.
![image uploaded from ios 1](https://cloud.githubusercontent.com/assets/1707538/23336960/c1918968-fba4-11e6-9bdb-2821d925ffb5.jpg)
![image uploaded from ios](https://cloud.githubusercontent.com/assets/1707538/23336961/c1920352-fba4-11e6-9c21-166268469f6e.jpg)

**Comment by seejessicacode** [comment]
Are you requesting reimbursement?

**Comment by jdungan** [comment]
yes.  I've sent a request to $techlahoma via the stripe cash app.

**Comment by groovecoder** [comment]
I can verify that @jdungan bought this for January meetup. @seejessicacode @amandaharlin should I go ahead and sign into the $techlahoma squarecash account to approve? Or do you want to do it yourself so you've got tabs on everything that goes thru there?

**Comment by seejessicacode** [comment]
This is @amandaharlin's call as treasurer. @jdungan the first receipt only doesn't list goods or services on the receipt, it only shows the total. Can you elaborate what that expense was for?

**Comment by jdungan** [comment]
I'm sorry I did not include the details and thanks for being careful.  It was for 100 hot dogs, chili, cheeze, etc.

**Comment by seejessicacode** [comment]
mmmmm, yummmy!

**Comment by groovecoder** [comment]
Oh yeah that was Coney I-lander day. Sorry I missed it!

**Comment by seejessicacode** [comment]
Has this been reimbursed? @groovecoder @jdungan

**Comment by jdungan** [comment]
Nope.  The cash.me request expired last night.  Would you like me to resubmit?

**Comment by seejessicacode** [comment]
yes please, and tag @groovecoder when you do. He's got a hand in the Techlahoma finances and I do not.

**Comment by groovecoder** [comment]
Approved via cash.me.
