### ISSUE TITLE
Update Zapier calendar entry for OKC Python's March meetup

### ISSUE THREAD

**Issue by kacollins** [techlahoma/user-groups#174]
The automation has the wrong date (Tuesday 3/7 instead of Wednesday 3/8) for this meetup:
https://www.meetup.com/Oklahoma-City-Python-Users-Group/events/237076510/

See #164.

**Comment by seejessicacode** [comment]
![image](https://cloud.githubusercontent.com/assets/943398/23508489/93cd6a94-ff17-11e6-9907-0dcc1e9021cf.png)
