### ISSUE TITLE
User group websites need to have links to StarSpace46 website

### ISSUE THREAD

**Issue by kacollins** [techlahoma/user-groups#197]
Include information in the wiki about linking from user group websites to StarSpace46 website

**Comment by blazedd** [comment]
Can we be sure to not make this Starspace specific? 36 Degrees North hosts our Tulsa events just too!

**Comment by the-simian** [comment]
@blazedd is right, we'll want to make sure to either specify the correct space-per-group or lead to another page that lists all the spaces we currently use. The groups in Tulsa, Bartelsville and Muskogee don't use SS46

**Comment by kacollins** [comment]
I created wiki pages for StarSpace46 and 36 Degrees North as requested!
