### ISSUE TITLE
Transfer UGs web domains to Techlahoma

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/user-groups#21]
## Only have a domain
- [ ] OKC LUGnuts
  - [okclugnuts.org](http://okclugnuts.org)
  - Domain is reserved
  - Website is gone
  - [x] Contact okclugnuts@gmail.com to invite them to transfer okclugnuts.org to Techlahoma and ask if they would like us to provide a Hexo website for them.
    - Sent email on 11/17/2016 at 2:15pm
- [x] Tulsa.rb
  - [tulsarb.org](http://tulsarb.org)
  - Url points to Meetup group
  - [x] Invite Wassim to transfer tulsarb.org to Techlahoma and ask if they would like us to provide a Hexo website for them.
    - Contacted on Meetup on 9/26 at 8:30pm
    - Tulsa.rb has opted out of transferring their domain and are okay with covering the charge themselves
## Have both a domain and website
- [ ] Code for OKC
  - [codeforokc.org](http://codeforokc.org)
  - [x] If not owned by Code for America, invite Matt Chandler to transfer codeforokc.org to Techlahoma.
    - Invited Code for OKC to transfer codeforokc.org to Techlahoma via Meetup msg on 11/17/2016 1:16 pm
  - Hosted on [https://github.com/codeforokc/codeforokc](https://github.com/codeforokc/codeforokc)
- [ ] ~~Code for Tulsa~~
  - ~~[codefortulsa.org](https://codefortulsa.org/about/)~~
  - [x] ~~If not owned by Code for America, invite Luke Crouch to transfer codefortulsa.org to Techlahoma.~~
    - ~~Invited Code for Tulsa to transfer codeforokc.org to Techlahoma via Meetup msg on 11/17/2016 1:20 pm~~
    - Luke Crouch confirmed that Code for America is currently providing their domain and promises to let Techlahoma know if that changes.
  - ~~Hosted on Wordpress?~~
- [x] Nerdy Girls
  - [nerdy-girls.org](http://nerdy-girls.org)
  - Techlahoma only sponsors Nerdy Girls Code Club, since there is not a separate website for that branch and NG doesn’t need a separate website for their code club
  - No further action needed.
- [x] OKC FP
  - [okcfp.com](http://okcfp.com)
  - Already own.
  - Hosted on [https://github.com/techlahoma/okcfp-website](https://github.com/techlahoma/okcfp-website)
  - No further action needed.
- [ ] OKC.js
  - [okcjs.com](http://okcjs.com)
  - [x] Invite Jesse Harlin to transfer okcjs.com to Techlahoma.
  - Hosted on [https://github.com/techlahoma/okcjs-website](https://github.com/techlahoma/okcjs-website)
- [ ] OKC JUG
  - [okcjug.org](http://okcjug.org)
  - [x] Invite Ryan Hoegg to transfer okcjug.org ownership to Techlahoma
    - Sent two emails and received no response. 9/27/2016 and 10/9/2016.
  - Hosted on Wordpress
- [ ] OKC MySql
  - [okcmysql.org](http://okcmysql.org)
  - [x] Invite Mike Benshoof to transfer okcmysql.org to Techlahoma
    - Messaged on Meetup on 11/17/2016 at 2pm
  - Hosted on Wordpress
- [ ] OKC Python
  - [okcpython.org]()
  - [x] Invite Mike Mattice to transfer okcpython.org to Techlahoma
    - Messaged on Meetup on 11/17/2016 at 2:07pm
  - Hosted on [https://github.com/techlahoma/okcpython-website](https://github.com/techlahoma/okcpython-website)
- [x] OKC Ruby
  - [okcruby.org](http://www.okcruby.org)
  - [x] Invite Jeremy Green to transfer okcruby.org to Techlahoma
  - Hosted on [https://github.com/okcruby/okcruby.github.io](https://github.com/okcruby/okcruby.github.io)
- [ ] OKC#
  - [okcsharp.net](http://okcsharp.net)
  - [x] Invite Matthew Reilly to transfer okcsharp.net to Techlahoma
    - Contacted on Meetup on 9/26 at 7:30pm
  - Hosted on [https://github.com/techlahoma/okcsharp-website](https://github.com/techlahoma/okcsharp-website)
-  [x] ~~Refresh OKC~~
  - ~~[refreshokc.org](http://refreshokc.org)~~
  - [x] ~~Invite Rick Shaw to transfer refreshokc.org to Techlahoma~~
    - Owner of domain is not responding.
  - Hosted on Wordpress
- [x] Tulsa Web Devs
  - [tulsawebdevs.org](http://tulsawebdevs.org)
  - [x] Invite Luke Crouch to transfer tulsawebdevs.org to Techlahoma
  - Where is tulsawebdevs.org hosted?
## Odd cases
- [ ] OK Game Devs
  - [okgd.org](http://okgd.org) or [okgamedev.com](http://okgamedev.com)
  - Two domains
    - One website points to their meetup group
    - The other is an actual website for the user group
  - [x] Contact James Simpson to invite him transfer one of the domains to Techlahoma and discuss which domain would be most appropriate for transfer.
    - Contacted on Meetup on 9/26 at 7pm
    - Contacted on Meetup again  on 11/17 at 1:55pm

**Comment by seejessicacode** [comment]
#18 
#19

**Comment by groovecoder** [comment]
tulsawebdevs.org is hosted on my hover.com account. It will renew in 3 days (sorry) ... can I transfer it? Does Techlahoma have a dnsimple.com account? Is it in our 1Password? Can I get a share?

**Comment by RicksConcepts** [comment]
Refresh is hosted on my personal server. It's built using WP and I maintain it. There are two domains for Refresh OKC. There's a .org and a .com both of which I do not own. The .org is owned by the original OKC chapter creator and I'm not sure he'll release it. I think Tommy at one point said he has the .com or maybe a different one.

Probably none of this made sense but figured I'd contribute.

**Comment by the-simian** [comment]
"Refresh is hosted on my personal server. It's built using WP and I maintain it." 

If you get abducted by UFO's  can anyone update the site? its word press so I'm guessing you've got other folks added int he admin panel/etc ?

**Comment by groovecoder** [comment]
C'mon that's ridiculous ... UFOs still have WiFi. They're not savages.

**Comment by seejessicacode** [comment]
We'll handle this as UGs request it.
