### ISSUE TITLE
Reimburse $$ for food/drink for Tulsa Game Developers | 2017-03-16

### ISSUE THREAD

**Issue by SenseiRAM** [techlahoma/user-groups#210]
What: Tulsa Game Developers
When: 03/16/2017 7:00 pm
Where: 36° North, Tulsa
9 RSVPs so far, typically about 15-20 show up.
https://www.meetup.com/Tulsa-Game-Developers/events/238226116/

Will likely opt for something cheapish like Dominos. (Sorry for such a late request!)

**Comment by seejessicacode** [comment]
@SenseiRAM will you be needing food for all TGD meetups going forward? I'm only asking because this is a first for TGD other than the reimbursement for cake--just trying to plan.

We have a system that will create these issues for select UGs who look to Techlahoma for food sponsorship, so if so I'll need to get TGD added into that.

**Comment by SenseiRAM** [comment]
I've done my best to get food donated in the past, but those avenues are running a little dry of late.

Would it be okay if we were added into the system? I don't know if we'll need it every month, but I do try to at least provide snacks when we can. That said, if you'd rather direct Techlahoma's funds to more established groups, I totally get that.

**Comment by seejessicacode** [comment]
Ah, no, don't sweat it! I was just asking for purely planning purposes.

To add TGD to our auto GH issue system, we need a pattern to identify which events to provide food for.

Looks like you're asking for help with food for [March Meeting: Heartland Gaming Expo with Roger Mailler!](https://www.meetup.com/Tulsa-Game-Developers/events/238226116/), but it appears you have regular Tulsa Hack nights as well. We currently only cover food once a month for each user group. So if we can't identify a pattern of which of TGD's events in a given month to provide grub for, then we're better off you making this issues as needed.

**Comment by groovecoder** [comment]
The TGD hack night coincides with TWD, so TWD covers them there.

@SenseiRAM - do you need me/us to order/buy the food for you before the March event, or are you okay with us reimbursing you via cash.me/$techlahoma like before?

**Comment by SenseiRAM** [comment]
Yeah, I just put Hack Night on our meetup so that our members are aware that they are welcome. I can remove it as a recurring event, if that makes things easier.

@groovecoder  I'm fine to reimburse like before. That worked well last time.

**Comment by seejessicacode** [comment]
I can set up the automation to create these issues for events that aren't called "Tulsa Hack Night"

**Comment by SenseiRAM** [comment]
Perfect!

**Comment by seejessicacode** [comment]
I'm going to leave this open and rename to clarify reimbursement. Thanks for answering my questions!

**Comment by seejessicacode** [comment]
You or Luke can close this after you've been reimbursed.

**Comment by SenseiRAM** [comment]
Here's the receipt. $33.74 after tip. Cash.me is $TheRichardM
Final headcount was 16, including a few new people who might become regulars. Really good meeting!

![img_6631](https://cloud.githubusercontent.com/assets/15986116/24057415/4d982654-0b15-11e7-8777-428318130baa.JPG)
![img_6632](https://cloud.githubusercontent.com/assets/15986116/24057416/4d9a27ce-0b15-11e7-9a49-70474a9441f4.JPG)

[Game devs March .pdf](https://github.com/techlahoma/user-groups/files/851356/Game.devs.March.pdf)

**Comment by seejessicacode** [comment]
@groovecoder can you close this after you reimburse?

**Comment by groovecoder** [comment]
Reimbursed via cash.me.
