### ISSUE TITLE
Setup a yearly process for current usergroups to reapply for Techlahoma sponsorship

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/user-groups#213]
Starting end of 2017, we want all current Techlahoma groups to reapply for sponsorship. The plan is to practice this every year.

Goals for this are:
- To give user groups an opportunity to judge if their relationship with Techlahoma is in their best interest
- To give the Techlahoma board an opening to review if the user group is in alignment with their mission and cooperative.

Action plan:
- [ ] Design a reapplication form
- [ ] Prepare template response to acknowledge submitted applications were received
- [ ] Establish a due date
  - Due date should be in the last quarter of the year, preferably no later than November so we have a chance to respond before the new year.
- [ ] Begin introducing this process in:
  - Email newsletter
  - Slack channel #usergroup-organizers
  - Meetup message to organizers only
- [ ] Decide how often and when the reminders should be
- [ ] Prepare template responses for the following scenarios:
  - No application was received by the due date, so we're stepping away and wish them well
  - We reviewed their application and our history with them over the past year and
    - have decided to step away but still wish them well.
    - are thrilled to resume working with them over the next year

**Comment by kacollins** [comment]
Fields to consider for the reapplication form:
Would like to continue as sponsored/affiliated group, switch between sponsored and affiliated, or discontinue relationship with Techlahoma?
Still agree to Code of Conduct?
Updated list of group leaders 
Any updates to other info on user group application
Confirmation that info in user group [folder](https://github.com/techlahoma/user-groups) is complete and correct
