### ISSUE TITLE
New User Group Submission: OKCQE - "Oklahoma City Quality Engineering"

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#253]
**Agree to CoC:** Yes
**Proposed group name:** OKCQE - "Oklahoma City Quality Engineering"
**City:** OKC
**Purpose:** Software quality engineering and testing strategies.
**Twitter:** Okc_QE
**Website:** 
**Would like help with:** Venue Assistance, Funding for Food & Drink, Audio & Video recording, Social Media / Announcement, Connecting to the greater OK communtiy

Submitted by Dale Spoonemore on 03/31/2017 13:41:13

**Comment by seejessicacode** [comment]
![image](https://cloud.githubusercontent.com/assets/943398/24626132/e8ef77de-1875-11e7-881d-58c76cae4202.png)
Received 4/3/2017

Dale has withdrawn his application, due to shift in career path.
