### ISSUE TITLE
New User Group Submission: Tulsa LUG

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#265]
**Agree to CoC:** Yes
**Proposed group name:** Tulsa LUG
**City:** Tulsa
**Purpose:** All things Linux
**Twitter:** 
**Website:** 
**Would like help with:** General Mentorship, Connecting to the greater OK communtiy

Submitted by Blixa Morgan on 04/11/2017 19:19:49

**Comment by seejessicacode** [comment]
Blixa Morgan's GH handle is @mrmakeit

**Comment by seejessicacode** [comment]
@mrmakeit Could you complete the bold items below? After you do, I should have enough info to present to the board.

- Purpose: All things Linux
- **Who will be the UG leaders/volunteers?** _(Need at least 2 leaders and 1 volunteer)_
- **Provide some example topics to be covered in this meetup.**
  - ...
  - ...
  - ...
- **Would like a lunch, evening, or weekend meetup time?**
- **Would Tulsa LUG like help with which of the following?**
   - [ ] **Venue Assistance**
   - [ ] **Funding for Food & Drink**
   - [ ] **A/V recording/streaming**

**Comment by seejessicacode** [comment]
Due to lack of response, the board has motioned to close this issue. Tulsa LUGnuts is welcome to reapply if they change their mainds.
