### ISSUE TITLE
Report expenses, group, stats, and submit reimbursement request for Tulsa Game Devs event | 2017-05-18

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#266]
What: May Meeting: Unity Development 101 (with C#)
When: 2017-05-18 6:00 PM
Where: 36 E Cameron Street, Tulsa
See Meetup event for final RSVP count: https://www.meetup.com/Tulsa-Game-Developers/events/239281872/

To requesting reimbursement, please complete the following steps:
- [ ] Picture of receipt(s)
- [ ] Final head count
- [ ] Photo of meetup in action
- [ ] Submit request for reimbursement at https://cash.me/$techlahoma

**Comment by SenseiRAM** [comment]
Final headcount: 28

Super successful meeting! We have lots more pictures if Techlahoma is interested in posting any.

![receipt](https://cloud.githubusercontent.com/assets/15986116/25283281/d84bf702-2678-11e7-8353-19f0887bbbc7.PNG)

![img_9028 1](https://cloud.githubusercontent.com/assets/15986116/25283472/8866ed9a-2679-11e7-9fb3-509916c5ab78.jpg)

**Comment by SenseiRAM** [comment]
Reimbursement request sent.

**Comment by seejessicacode** [comment]
@SenseiRAM I think you meant to update #264

This issue is for the May meetup, it was created when you scheduled it on Meetup.com

**Comment by SenseiRAM** [comment]
Okay, now I'm updating the _correct_ issue! I took the photo after the presentation was over. We should have an archive of the presentation once Blixa fixes an issue with the video.

Final headcount: 15

[Tgd-may-2017-chips.pdf](https://github.com/techlahoma/user-groups/files/1019250/Tgd-may-2017-chips.pdf)

![tgdmay2017](https://cloud.githubusercontent.com/assets/15986116/26315183/e90263e0-3ed5-11e7-9652-9bfd5d9dfd23.jpg)

**Comment by seejessicacode** [comment]
@SenseiRAM I see you submitted a reimbursement request. Could you please post the receipt here first?

**Comment by SenseiRAM** [comment]
Should be in the PDF linked in the above post. I'll put it here just in case it's not showing up: 
[Tgd-may-2017-chips.pdf](https://github.com/techlahoma/user-groups/files/1019755/Tgd-may-2017-chips.pdf)

**Comment by seejessicacode** [comment]
Ah okay! The name didn't tip me off, my bad for not even clicking it.

**Comment by seejessicacode** [comment]
Reimbursment request has been approved! Thanks!
