### ISSUE TITLE
Existing User Group Submission: Oklahoma Agile Alliance

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#274]
**Agree to CoC:** Yes
**Group name:** Oklahoma Agile Alliance
**Purpose:** 
**Current location:** Credit Union House 
**Current meeting date and time:** Third Thursday of the Month
**Leadership:** Dianna DeMotto, Justin Blackwelder, Shane Fry
**Avg. # of attendees:** 20-40 member per month
**Avg. cost per meeting:** $30
**Who sponsors your group:** Recruiters, Organizers' company, Other
**Twitter:** 
**Website:** 
**Would like help with:** General Mentorship, Social Media / Announcement, Connecting to the greater OK communtiy

Submitted by Justin Blackwelder on 04/18/2017 17:16:03

**Comment by seejessicacode** [comment]
No website was provided, but I found this Meetup group: https://www.meetup.com/Agile-Practioners-Technology-Meetup/

**Comment by seejessicacode** [comment]
Oklahoma Agile Alliance is not listed in https://www.agilealliance.org/communities/

**Comment by seejessicacode** [comment]
No GH handles found for any of the listed leaders
