### ISSUE TITLE
Existing User Group Submission: OKC TUG - Oklahoma City Tableau User Group

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#279]
**Agree to CoC:** Yes
**Group name:** OKC TUG - Oklahoma City Tableau User Group
**Purpose:** 
**Current location:** Dell campus 
**Current meeting date and time:** The third Wednesday of the month @12:00
**Leadership:** Guillermo Mendez-Kes -  Guillermo.Mendez-Kes@dell.com
Matthew Reily - me@mattreily.com - 405-808-8403
**Avg. # of attendees:** 20-30
**Avg. cost per meeting:** $0
**Who sponsors your group:** Organizers' company
**Twitter:** okctug
**Website:** http://community.tableau.com/groups/oklahoma-city
**Would like help with:** General Mentorship, Social Media / Announcement, Connecting to the greater OK communtiy

Submitted by Matthew Reily on 04/26/2017 7:00:43

**Comment by seejessicacode** [comment]
The board has voted to on board OKC TUG as an affiliated user group.
This means we will
- [ ] add OKC TUG to the affiliated user group section of our user group page (https://www.techlahoma.org/usergroups)
- [ ] include OKC TUG in our social media announcements

In order to identify how to include OKC TUG in our social media announcements, we first need to identify how to listen for new events. @matthewreily can you help us?

**Comment by seejessicacode** [comment]
@matthewreily, 
I need confirmation that this inventory folder I setup is up to date: https://github.com/techlahoma/user-groups/tree/master/affiliated/OKC-Tableau

**Comment by seejessicacode** [comment]
I was recently informed that Techlahoma can provide a meetup group for OKC Tableau and other affiliated UGs. Is this something you would use? I noticed you're currently relying on email to track RSVPs.

**Comment by seejessicacode** [comment]
OKC TUG can't not (double negative intended) use EventBrite, so we can't automate their announcements. 

@matthewreily is the inventory folder I reference above up-to-date? Your confirmation is all I need to close this issue.

**Comment by seejessicacode** [comment]
@matthewreily answer meeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by seejessicacode** [comment]
I'm adding Kimberly on to help. The UG committee needs to reach a point where there's more than 1 person who can organize the on-boarding.

**Comment by matthewreily** [comment]
@seejessicacode good question on how we would know when a meeting is occurring.  Currently, they are scheduled for the 3rd Tuesday of the month from 11:30 - 12:30.  I believe the only current automated notifications are via email.  Do we want to sign up an account to listen for this or should we ask the leaders to email Techlahoma separately with upcoming meeting details?

Is there something you would prefer?

**Comment by matthewreily** [comment]
@seejessicacode yes the folder is up to date.

**Comment by seejessicacode** [comment]
oops, closed this issue too soon. If you can get info@techlahoma.org added to the OKC TUG email list, we can _try_ to parse the event details and store them in the okcUGs gCal where we schedule all the slack/social media posts.
