### ISSUE TITLE
Arrange food and drink for OKC JUG event | 2017-05-11

### ISSUE THREAD

**Issue by jasondlee** [techlahoma/user-groups#288]
Brian Sheldon

WebSockets

(Apologies for the late notice)

**Comment by seejessicacode** [comment]
These type of issues are automatically generated when you schedule the event on https://www.meetup.com/okcjug/. We require UGs to schedule the meetup event in order to plan announcements, food, etc.

**Comment by jasondlee** [comment]
Thanks. Couldn't remember the process. I'll do that now.
