### ISSUE TITLE
New User Group Submission: OKCPBI - Oklahoma City Power BI User Group

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#299]
**Agree to CoC:** Yes
**Proposed group name:** OKCPBI - Oklahoma City Power BI User Group
**City:** OKC
**Purpose:** Microsoft Power BI, Data Analysis Expressions (DAX), related MS Azure topics
**Twitter:** 
**Website:** 
**Would like help with:** General Mentorship, Venue Assistance, Event Insurance, Funding for Food & Drink, Audio & Video recording, Social Media / Announcement, Connecting to the greater OK communtiy

Submitted by Thomas Bruton on 05/05/2017 8:32:46

**Comment by seejessicacode** [comment]
Applicant's GH handle is @thomasdbruton

**Comment by thomasdbruton** [comment]
What are next steps in the application process?

**Comment by matthewreily** [comment]
Hey @thomasdbruton glad to see you are wanting to join Techlahoma.  We have a couple of items that need to be addressed before we can determine where we can fit your group in.

**Comment by thomasdbruton** [comment]
Thank you for the clarification.  How about OKC Business Intelligence and Visual Analytics?

**Comment by seejessicacode** [comment]
There are also two other important things to note:
1. the board must review finances and future projections before voting to approve your application
2. the UG must have at least 2 leaders to ensure the UG has a chance survive when one leader is unavailable or the application will be declined.

So UG name aside, can you
- name a co-leader
- redefine the purpose of the UG (This will be your group description so a mission statement supplemented with examples would be great, just be sure the examples are limited to for profit products)

**Comment by thomasdbruton** [comment]
can you clarify limiting examples to for profit products?

**Comment by seejessicacode** [comment]
Sorry, I meant list examples that are not limited to for-profit products

**Comment by seejessicacode** [comment]
Techlahoma board meeting is next week. Are there any updates? Are you still interested in starting this UG, @thomasdbruton?

**Comment by seejessicacode** [comment]
Due to lack of response, I am closing this issue. Please feel free to apply again when you have more info.
