### ISSUE TITLE
New User Group Submission: Tulsa Game Developers

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/user-groups#30]
**Agree to CoC:** Yes
**Proposed group name:** Tulsa Game Developers
**City:** Tulsa
**Purpose:** We would discuss the principles and technologies used in game design, and we would provide a collaborative space for all individuals interested in creating games (digital, physical or otherwise)
**Twitter:** TulsaGameDevs
**Website:** http://www.facebook.com/groups/434560433409848/
**Would like help with:** Funding for Food & Drink, Audio & Video recording, Connecting to the greater OK communtiy

Submitted by Richard Mitchell on 11/04/2016 15:30:14

**Comment by groovecoder** [comment]
#52 is the right issue for this group.
