### ISSUE TITLE
wiki images

### ISSUE THREAD

**Issue by the-simian** [techlahoma/user-groups#32]
![login](https://cloud.githubusercontent.com/assets/954596/20248915/14958260-a9b4-11e6-8332-a585b6b6630c.PNG)
![selected_group](https://cloud.githubusercontent.com/assets/954596/20248939/e26bf16a-a9b4-11e6-946a-23876fb7bdd0.PNG)
![pnding](https://cloud.githubusercontent.com/assets/954596/20248956/232ab24a-a9b5-11e6-9bd6-9942549dd3a1.PNG)
![techlahoma-approve-1](https://cloud.githubusercontent.com/assets/954596/20248969/72e3f6d4-a9b5-11e6-84ef-0d0707ed3fce.PNG)
![approve-pending](https://cloud.githubusercontent.com/assets/954596/20248981/a5388d8e-a9b5-11e6-8fff-6002c9290ccd.PNG)
Approve the member.
![approve-me](https://cloud.githubusercontent.com/assets/954596/20248995/d47d9350-a9b5-11e6-9728-bf50259592e2.PNG)

![approve-member](https://cloud.githubusercontent.com
![manage-roles-2](https://cloud.githubusercontent.com/assets/954596/20249027/56de6a54-a9b6-11e6-81de-77ef465137a6.PNG)
![manage-roles](https://cloud.githubusercontent.com/assets/954596/20249028/56e968e6-a9b6-11e6-9e24-f1029bb9ea28.PNG)

/assets/954596/20249004/fd43d93e-a9b5-11e6-836b-103bf3a1ec5c.PNG)

**Comment by seejessicacode** [comment]
<img width="476" alt="createmeetup" src="https://cloud.githubusercontent.com/assets/943398/20467330/f74f410e-af4a-11e6-80a2-1b121b390f8a.PNG">

**Comment by seejessicacode** [comment]
<img width="474" alt="createmeetup" src="https://cloud.githubusercontent.com/assets/943398/20636158/76c4ebb0-b32d-11e6-8fff-52481663f311.PNG">

**Comment by seejessicacode** [comment]
<img width="724" alt="groupsettings" src="https://cloud.githubusercontent.com/assets/943398/20644159/04ccad80-b3f1-11e6-824e-395a6af82a0b.PNG">
<img width="424" alt="yourmembers" src="https://cloud.githubusercontent.com/assets/943398/20644161/09c5aee0-b3f1-11e6-9d89-e68f92cbed3b.PNG">
<img width="524" alt="welcomemessage" src="https://cloud.githubusercontent.com/assets/943398/20644162/0e7f49d2-b3f1-11e6-8213-b74831d7d582.PNG">

**Comment by seejessicacode** [comment]
<img width="727" alt="groupdescription" src="https://cloud.githubusercontent.com/assets/943398/20644377/021dcaa4-b3f8-11e6-9f1d-ab3d575103d2.PNG">
<img width="682" alt="editgroupdescription" src="https://cloud.githubusercontent.com/assets/943398/20644379/06bc1854-b3f8-11e6-86cf-9f98f0eefb0a.PNG">
