### ISSUE TITLE
New User Group Submission: Makers of Oklahoma (MOO)

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/user-groups#33]
**Agree to CoC:** Yes
**Proposed group name:** Makers of Oklahoma (MOO)
**City:** OKC
**Purpose:** "Maker" subjects of all sorts. From Internet of Things projects including Raspberry Pi and Arduino integration, to electronics of all sorts, to woodworking and metal working. Making things!
**Twitter:** MakersofOK
**Website:** http://www.facebook.com/groups/MakersofOklahoma/
**Would like help with:** General Mentorship, Venue Assistance, Event Insurance, Funding for Food & Drink, Audio & Video recording, Social Media / Announcement, Connecting to the greater OK communtiy

Submitted by Derek Hubbard on 11/16/2016 1:24:05

**Comment by the-simian** [comment]
I'm not gonna lie I love this group name.

**Comment by seejessicacode** [comment]
https://github.com/techlahoma/board_meetings/blob/master/2016/12_december-minutes.md

Email sent.
