### ISSUE TITLE
New User Group Submission: Code.org  Workshops or Hour of Code

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#346]
**Agree to CoC:** Yes
**Proposed group name:** Code.org  Workshops or Hour of Code
**City:** OKC
**Purpose:** Tech beginning code using Code.org
**Twitter:** skcteacher
**Website:** 
**Would like help with:** General Mentorship, Venue Assistance, Funding for Food & Drink, Audio & Video recording, Social Media / Announcement, Connecting to the greater OK communtiy

Submitted by Shelly K Cherry on 06/12/2017 20:42:02

**Comment by kacollins** [comment]
Is this group intended to be targeted toward children or adults?

**Comment by seejessicacode** [comment]
We have a similar group that meets this need called [freeCodeCamp OKC](https://www.meetup.com/FreeCodeCampOKC/). They meet every Sunday.

The reason I am pointing this out is that the request for venue assistance and funding for food and drink is a costly expense. The board members are not likely to approve this application if it is not meeting a unique need to justify the expense.

**Comment by seejessicacode** [comment]
> Thanks,
>
>Don't worry about it. I am a facilitor for this program and teach students to code and I also host teacher workshops. I will just keep doing this code on my own.
>
>Shelly

Bummer! I hope if Shelly changes her mind that she'll reach out to fccokc. We sponsor fccokc so I bet if fccokc wanted to host something geared toward teachers, we could fund that.
