### ISSUE TITLE
Expenses for 6-6-2017 Tulsa Hack Night

### ISSUE THREAD

**Issue by jdungan** [techlahoma/user-groups#351]
![img_2485](https://user-images.githubusercontent.com/1707538/27364261-1447faca-55ff-11e7-86ef-b9f6ca8cb4c5.JPG)

**Comment by seejessicacode** [comment]
Were you not able to to assign or tag anyone in this issue? I'll review your permissions on our GH team. I was worried that an almost $300 reimbursement was approved with seemingly zero documentation. I only found this while checking my GH notifications.

We also ask UG leaders to provide a head count and a photo of the meetup in action for reimbursement. This helps us crunch the numbers for town halls and show case recent photos of UGs.

**Comment by seejessicacode** [comment]
Sent you an invite to join the UG leader team which should give you more permissions.

**Comment by seejessicacode** [comment]
Alright, I've set up an automation that created this when I tested it. So we've yet to confirm that it's working without human intervention.

Please update https://github.com/techlahoma/user-groups/issues/363 when you're submitting a reimbursement request for July's hack night
