### ISSUE TITLE
Book StarSpace46 for Systems Management in OKlahoma Experts | 12/19/2016 7:00 PM

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#36]
What: Party like it's 1999
When: 12/19/2016 7:00 PM
Where: StarSpace 46

Check meetup for RSVP count: https://www.meetup.com/Systems-Management-in-OKlahoma-Experts/events/235904907/

**Comment by seejessicacode** [comment]
Test for tonight's meeting. Please discard AFTER 11/29/2016
