### ISSUE TITLE
New User Group Submission: Texoma Coders

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#417]
**Agree to CoC:** Yes
**Proposed group name:** Texoma Coders
**City:** Other
**Purpose:** All aspects of coding in general, from front end to back end and full-stack development.
**Twitter:** TexomaCoders
**Website:** https://www.facebook.com/groups/492652307741260/
**Would like help with:** General Mentorship, Venue Assistance, Funding for Food & Drink, Social Media / Announcement, Connecting to the greater OK communtiy

Submitted by Levi Hornsby on 08/18/2017 16:13:46

**Comment by matthewreily** [comment]
@seejessicacode sent Levi an email asking for another co-leader as well as a confirmation on a meeting place.
