### ISSUE TITLE
Tulsa Data Science

### ISSUE THREAD

**Issue by tk2u** [techlahoma/user-groups#471]
Has leadership at TDS-UG made Techlahoma Organizer of UG?

**Comment by seejessicacode** [comment]
Yes. https://www.meetup.com/Tulsa-Data-Science-Meetup/members/?op=leaders

Just waiting on @jamesbenharris and @deeceefar2 to answer https://github.com/techlahoma/user-groups/issues/126#issuecomment-302904025
