### ISSUE TITLE
Book StarSpace46 for CocoaHeads OKC

### ISSUE THREAD

**Issue by billygoat** [techlahoma/user-groups#486]
What: TBA with Brian Clubb
When: 10/24/2017 11:30 am
Where: StarSpace 46

Check meetup for RSVP count: https://www.meetup.com/CocoaHeads-OKC/events/244151109/

This is not our normal day (because SS46 is booked that day) so I wanted to make sure this date/time is still available.

cc @seejessicacode

**Comment by seejessicacode** [comment]
I wonder why this wasn't automatically created when the event was scheduled. I'll look into that.

![image](https://user-images.githubusercontent.com/943398/31907218-cdda60a8-b7f8-11e7-9e95-1dad0d1b3fde.png)

**Comment by seejessicacode** [comment]
Okay, the automation didn't work because the venue name was set to "Star Space 46" instead of "StarSpace46". The latter is the official naming, but I tweaked the automation to be a little more flexible on the spelling.
