### ISSUE TITLE
Existing User Group Submission: Oklahoma City Salesforce Developer Group

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#51]
**Agree to CoC:** Yes
**Group name:** Oklahoma City Salesforce Developer Group
**Purpose:** 
**Current location:** Symphony Talent, 5th Street, Edmond OK - formerly at the 404, and potentially splitting between Starspace and Edmond location soon (based on feedback from group at next meet) 
**Current meeting date and time:** Sparse currently, in rebuilding mode, targeting new pattern of 2 meetings per month, 1 virtual meeting every 2 weeks, and 1 in person hands on or presentation style meeting (week structures to be determined this Friday)
**Leadership:** Salesforce (community dev relations group) - Meetup leader, marketing efforts, content, resources, financial support, etc. (primary sponsor)
Richard Tuttle - Leader
David Kelly - Co-Leader
**Avg. # of attendees:** 5-10
**Avg. cost per meeting:** $75
**Twitter:** 
**Website:** http://www.meetup.com/Oklahoma-City-Salesforce-Developer-Group/
**Would like help with:** General Mentorship, Social Media / Announcement, Connecting to the greater OK communtiy

Submitted by Richard Tuttle on 12/07/2016 16:07:50

**Comment by seejessicacode** [comment]
As of 12/20/2016, 12 user groups applications were pending approval and Techlahoma could only commit to support 8 of those groups.

Unfortunately, OKC Salesforce Developer Group was not approved for the following reasons:
- Salesforce is a company product
- High cost ([estimated financials and discussion](https://github.com/techlahoma/planning/issues/41#issuecomment-268377329))

**Comment by seejessicacode** [comment]
https://github.com/techlahoma/board_meetings/blob/master/2016/12_december-minutes.md

Email sent.
