### ISSUE TITLE
Arrange food, drink, and venue access for OKC# event | 2018-01-08

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#521]
What: Lightning Talks
When: 01/08/2018 11:30 am
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/OKC-Sharp/events/245214158/

For @matthewreily:
- [x] Order delivery unless you have written confirmation from a UG leader that they will pick up the order
- [x] Post picture of order here. Please include pickup time and location or delivery time if not included in image

For the UG leadership (@kacollins @matthewreily @dannyburrows @davidroberts63):
Please follow up with the following:
 - [x] Picture of receipt(s)
 - [x] Final head count
 - [x] Photo of meetup in action
 - [x] Any food or food service feedback (was it on time, how much was left over, was the service adequate, etc)

**Comment by matthewreily** [comment]
![screen shot 2018-01-08 at 6 07 33 am](https://user-images.githubusercontent.com/8399844/34670069-4fde1f36-f43a-11e7-96b9-c2a1b29dd698.png)
![screen shot 2018-01-08 at 6 06 02 am](https://user-images.githubusercontent.com/8399844/34670070-4ff4049a-f43a-11e7-8f2f-412cab992934.png)

**Comment by kacollins** [comment]
27 attendees. The pizza arrived a few minutes early.

![image](https://user-images.githubusercontent.com/15042297/34684308-562b4136-f46a-11e7-8015-4d75403c718d.png)

**Comment by kacollins** [comment]
A few pieces of pizza were left over.

![image](https://user-images.githubusercontent.com/15042297/34688597-4bb06bc4-f478-11e7-8dcb-4c9ea0702666.png)
