### ISSUE TITLE
New User Group Submission: OKC Analytics

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#523]
**Agree to CoC:** Yes
**Proposed group name:** OKC Analytics
**City:** OKC
**Purpose:** Data cleaning, manipulation, statistical modeling, API integration, data visualizations, etc. We would cover a wide range of topics related to the use of data and analytics across multiple fields.
**Twitter:** Okcanalytics
**Website:** 
**Would like help with:** General Mentorship, Venue Assistance, Event Insurance, Funding for Food & Drink, Audio & Video recording, Social Media / Announcement, Connecting to the greater OK communtiy

Submitted by Jessica Hale on 11/18/2017 12:55:30

**Comment by hyunjee-hale** [comment]
###Techlahoma New User Group Submission Form - UPDATE

* Proposed group name: OKC Analytics
* City: Greater OKC
* Purpose: To knowledge share best practices, key learnings and new features related to Analytics. We will cover collecting, cleaning, manipulating and modeling data, integrating with APIs, data visualizations, research, etc. We would cover a wide range of topics related to the use of data and analytics across multiple fields (advertising, marketing, health care, research)
	* Website: Google Analytics, Piwik, Organic Search
	* Social: Facebook, Instagram, Twitter, YouTube
	* Programmatic: Display, Native Advertising
	* Paid Search: AdWords, Bing
	* UX/Design: Data Driven Design, UX Research
	* Data Best Practices: Data Cleaning, Data Manipulation, Data Modeling. Tools covered SAS, R, Python (others will be added)
* Gmail: okc.analytics@gmail.com
* Twitter: okcanalytics
* Facebook: OKC Analytics / @okcanalytics
* Website: okcanalytics.com (we are working on getting the site up, but have purchased the domain)
* Current Chairs:
	* Jessica Hale: Senior Research Biostatistician @ OTRC, co-owner of CENIACK
		*  Data best practices
		*  Digital data collection
		*  SAS, R
	* Susan Simkins: Senior UX Developer @ BigWing, Author of several courses (https://www.pluralsight.com/authors/susan-simkins) and working on her first manuscript which will be out in Fall 2018
		* Data driven design
		* UX research
	* Rebecca Roper: SEM Specialist @ BigWing
		* Programmatic
		* Paid search
		* Social media analytics for advertising
	* Terry Hale: Senior Web Manager @ BigWing, owner of CENIACK
		* Digital data collection
		* Website analytics and implementation
		* Data visualization
		* API integrations
	* Sarah Hoffman: Senior Social Media Manager @ Staplegun
		* Social media analytics and best practices
