### ISSUE TITLE
Book StarSpace46 for OKC MySQL | 01/26/2017 7:00 pm

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#53]
What: January Meetup - Clustering and Group Replication
When: 01/26/2017 7:00 pm
Where: StarSpace 46

Check meetup for RSVP count: https://www.meetup.com/Oklahoma-City-MySQL-Meetup/events/236282249/

**Comment by seejessicacode** [comment]
![image](https://cloud.githubusercontent.com/assets/943398/21271437/9e29e2e2-c380-11e6-9798-ac13984d675c.png)
