### ISSUE TITLE
Book StarSpace46 for OKC JUG | 01/10/2017 11:30 am

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#54]
What: Topic TBD
When: 01/10/2017 11:30 am
Where: StarSpace 46

Check meetup for RSVP count: https://www.meetup.com/okcjug/events/236354888/

**Comment by seejessicacode** [comment]
![image](https://cloud.githubusercontent.com/assets/943398/21357838/64fa2864-c69c-11e6-9e8d-3cb619621098.png)
