### ISSUE TITLE
New User Group Submission: gokc - The Oklahoma City Golang User Group

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#55]
**Agree to CoC:** Yes
**Proposed group name:** gokc - The Oklahoma City Golang User Group
**City:** OKC
**Purpose:** Golang and its ecosystem for work and for sport.
**Twitter:** okcgolang
**Website:** 
**Would like help with:** General Mentorship, Venue Assistance, Event Insurance, Funding for Food & Drink, Audio & Video recording, Social Media / Announcement, Connecting to the greater OK communtiy

Submitted by John Pettigrew on 12/21/2016 14:02:53

**Comment by seejessicacode** [comment]
@john-pettigrew The board will be discussing on boarding more user groups soon.

Can you list who the organizer and co-organizers will be? It's important to Techlahoma that user groups have at least 2 leaders (extra points for 1 or 2 volunteers) to ensure the stability of the user group.

**Comment by seejessicacode** [comment]
@john-pettigrew ?

**Comment by john-pettigrew** [comment]
@seejessicacode I believe there is now a go group. (https://www.okgo.coffee/). So I think I would rather hold off for now. Thanks!
