### ISSUE TITLE
Tulsa Agile Practitioners Event Dates Moved

### ISSUE THREAD

**Issue by jugisahunk** [techlahoma/user-groups#558]
We moved our event dates up a week in the month this month. Instead of happening next week, Lean Coffee Lunch and This Month on TAP have been moved to the 16th and the 18th respectively.

@seejessicacode told me I could create an issue here to ensure the notifications go out properly.

Here are the links for reference:

https://www.meetup.com/TulsaAgilePractitioners/events/245893283/
https://www.meetup.com/TulsaAgilePractitioners/events/246447333/

**Comment by seejessicacode** [comment]
Just to clarify, does this date change only affect this month or does it also affect all following months?

**Comment by jugisahunk** [comment]
Just for this month. Thank you :)

**Comment by seejessicacode** [comment]
I got these entries in the queue! I did notice that there are no other posts drafted/scheduled for TAP events scheduled after January, so I'll give that looky.

You should see announcements posted for the above events 3 hours in advance.
