### ISSUE TITLE
Arrange food and drink for OKC FP | 2017-01-31

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/user-groups#56]
What: OKC Functional Programming
When: 1/31/2017 11:30 AM
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/OKC-FP/events/236384878/

**Comment by amandaharlin** [comment]
<img width="583" alt="screen shot 2017-01-30 at 5 29 26 pm" src="https://cloud.githubusercontent.com/assets/716644/22446342/b8c91aaa-e711-11e6-900e-388af96f2f3d.png">

**Comment by amandaharlin** [comment]
✔ordered pizza for fp

**Comment by jordan-parmer** [comment]
Picture of receipt. We had one pizza left over. 

29 people showed up. We were roughly 10 people short of the RSVP count.

![img_20170131_111817](https://cloud.githubusercontent.com/assets/5378348/22480224/50389092-e7b6-11e6-9b35-3815a1b876cf.jpg)

**Comment by jordan-parmer** [comment]
![img_20170131_115132](https://cloud.githubusercontent.com/assets/5378348/22480375/cd64d3a0-e7b6-11e6-968f-d797bb481155.jpg)
![img_20170131_115146](https://cloud.githubusercontent.com/assets/5378348/22480374/cd62c6fa-e7b6-11e6-8bc0-d1b5c14c6185.jpg)
![img_20170131_115208](https://cloud.githubusercontent.com/assets/5378348/22480373/cd62a9fe-e7b6-11e6-9f5e-0cd9b52e3f39.jpg)
![img_20170131_120605](https://cloud.githubusercontent.com/assets/5378348/22480372/cd625e7c-e7b6-11e6-8fe8-f752fa8e47bb.jpg)

**Comment by amandaharlin** [comment]
WOW! great photos. thanks so much for the pizza info too!
