### ISSUE TITLE
TAP: Social Media posts not scheduled in gCal

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/user-groups#573]
https://www.meetup.com/TulsaAgilePractitioners

Check Zapier and search for the problem and/or solution to automating posts

**Comment by seejessicacode** [comment]
@jugisahunk as I am investigating this, I am seeing that you're using indefinite repeating events for the TAP meetup group. While that is an awesome feature, Meetup doesn't really offer a means to trigger to an update to our social media calendar or its post contents. Meetup up also only triggers "new event" event a for meetups over a year in advance for existing event series. 

This means that 
- if you change the meeting name, frequency, or date/time for the indefinite future, then our volunteers have a lot of calendar cleanup to do
- any events already existing when we need to fix a bug or update our code will be ignored and then we gotta manually update the calendar for n-many events for a single user group.

I've been asking other user group leaders to limit their repeating events to 4-6 months as this limit will still give UG leaders automate their meetups, but still give them the ability to make any logistical changes without risking error in our social media calendar and excessive data entry work on the volunteers.

I can make this change for TAP if you like, but I want to make sure you have a chance to share any questions or comments you have.

**Comment by jugisahunk** [comment]
Sure, go ahead and make the change :).

**Comment by seejessicacode** [comment]
Done! Thanks @jugisahunk! Please take a look at https://www.meetup.com/TulsaAgilePractitioners/events/ and let me know if I butchered something. I will return focus to making sure the TAP events are recorded in our social media calendar.

**Comment by seejessicacode** [comment]
This looks to be working again. Don't hesitate to hit us up again!
