### ISSUE TITLE
Error in OKC Python chron job generating wrong date

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/user-groups#604]
This error risks not booking the event center in time and OKC Python losing their meetup venue.
UG leaders didn't report that we didn't secure the venue for them and I didn't notice until the issue was generated and I was looking up the event url to include in their venue reservation. So this resulted in day-of scrambles.

https://github.com/techlahoma/user-groups/issues/603#issuecomment-356603296

**Comment by mmattice** [comment]
Hey!  Where's the code for this?  Perhaps we can help you out?

I don't seem to have access to the booking system, so I can't tell if it's booked.

**Comment by kacollins** [comment]
I just realized that this bug caused the Python meetup to be added to the user group calendar for 1/24. I'll go ahead and delete that. I believe the bug is in calculating whether a Wednesday is the last Wednesday of the month and this will happen each Wednesday until it's fixed.

**Comment by kacollins** [comment]
I deleted the entry on the user group calendar for 1/31.

**Comment by seejessicacode** [comment]
Thank you! I forgot about that!

**Comment by seejessicacode** [comment]
I think I got this fixed somehow Zapier lost the value of the month of day computed 1 week from the current Wednesday (used to check if the current Wednesday is the last Wednesday of the month). I don't know what caused it but the test runs are back in order.

**Comment by seejessicacode** [comment]
I think it's working again!! Nothing was falsely created last week and trigger correctly executed today!
![giphy](https://user-images.githubusercontent.com/943398/35625196-0ef3e99a-0657-11e8-86eb-8600f3bf8273.gif)
