### ISSUE TITLE
Request reimbursement for food and drink for Refresh OKC event | 2018-02-28

### ISSUE THREAD

**Issue by kacollins** [techlahoma/user-groups#674]
What: A Study in User Experience
When: 02/28/2018 11:30 am
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/Refresh-OKC/events/246616761/

To request reimbursement, please complete the following steps:
- [ ] Post picture of receipt(s) in this thread
- [ ] Post photo(s) of the meetup in action on your meetup event
- [ ] Submit [request for reimbursement](https://github.com/techlahoma/user-groups/wiki/Requesting-Reimbursement) from $techlahoma on https://cash.me within 1 month of the event

Any questions about reimbursement may be referred to the board treasurer.

cc @tanimale @susansimkins

**Comment by rshawokc** [comment]
This will not be needed. Thank you.
