### ISSUE TITLE
Request reimbursement for food and drink for OKCGD event | 2018-02-01

### ISSUE THREAD

**Issue by kacollins** [techlahoma/user-groups#685]
What: Lightning Talks
When: 02/01/2018 7:00 pm
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/Oklahoma-Game-Developers/events/246941801/

To request reimbursement, please complete the following steps:
- [x] Post picture of receipt(s) in this thread
- [x] Post photo(s) of the meetup in action on your meetup event
- [x] Submit [request for reimbursement](https://github.com/techlahoma/user-groups/wiki/Requesting-Reimbursement) from $techlahoma on https://cash.me within 1 month of the event

Any questions about reimbursement may be referred to the board treasurer.

cc @goldfire, @okaybenji

**Comment by goldfire** [comment]
![img_9862](https://user-images.githubusercontent.com/882005/35738562-d5cb096a-07f4-11e8-9ac5-fdcc14e1f811.jpg)

**Comment by kacollins** [comment]
![image](https://user-images.githubusercontent.com/15042297/35835673-a2b7932c-0aa1-11e8-88f1-7ffeedc653ff.png)
