### ISSUE TITLE
Request reimbursement for food and drink for OKC.js | 2018-02-20

### ISSUE THREAD

**Issue by kacollins** [techlahoma/user-groups#723]
What: Double Feature: Pong in Native JS with Aaron Krauss/Babylon.js with Jesse Harlin
When: 02/20/2018 11:30 am
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/OKC-js/events/247259379/

To request reimbursement, please complete the following steps:
- [x] Post picture of receipt(s) in this thread
- [ ] Post photo(s) of the meetup in action on your meetup event
- [ ] Submit [request for reimbursement](https://github.com/techlahoma/user-groups/wiki/Requesting-Reimbursement) from the Techlahoma Foundation on https://venmo.com within 1 month of the event

Any questions about reimbursement may be referred to the board treasurer.

cc @the-simian @amandaharlin @vlucas

**Comment by seejessicacode** [comment]
Running total: $118.86

Chicken: $107.38
![okcjsreceipt](https://user-images.githubusercontent.com/943398/36437051-99cc8160-162b-11e8-9de8-ddeece5a4917.jpg)
Drinks: $11.48
![okcjsreceipt 2](https://user-images.githubusercontent.com/943398/36437163-e19c246e-162b-11e8-83dd-859271100a71.jpg)

**Comment by amandaharlin** [comment]
<img width="1145" alt="screen shot 2018-02-24 at 12 41 04 pm" src="https://user-images.githubusercontent.com/716644/36633831-6e2c5042-1961-11e8-8ebd-a689e5d15448.png">
<img width="1144" alt="screen shot 2018-02-24 at 12 52 30 pm" src="https://user-images.githubusercontent.com/716644/36633851-abe6e58c-1961-11e8-9e86-33dcc368d089.png">

**Comment by amandaharlin** [comment]
has there been any movement on the venmo problem? i can't request reimbursement because the techlahoma account is using my phone number.

**Comment by kacollins** [comment]
What is the status on this? The reimbursement request is due a week from tomorrow.

**Comment by amandaharlin** [comment]
@kacollins request has been sent to the techlahoma venmo account 👍
