### ISSUE TITLE
Request reimbursement for food and drink for OKC.js | 2018-03-20

### ISSUE THREAD

**Issue by kacollins** [techlahoma/user-groups#724]
What: Lightning Talks
When: 03/20/2018 11:30 am
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/OKC-js/events/247261051/

To request reimbursement, please complete the following steps:
- [x] Post picture of receipt(s) in this thread
- [x] Post photo(s) of the meetup in action on your meetup event
- [x] Submit [request for reimbursement](https://github.com/techlahoma/user-groups/wiki/Requesting-Reimbursement) from the Techlahoma Foundation on https://venmo.com within 1 month of the event

Any questions about reimbursement may be referred to the board treasurer.

cc @the-simian @amandaharlin @vlucas

**Comment by the-simian** [comment]
![image](https://user-images.githubusercontent.com/954596/37730745-7450d978-2d0e-11e8-8ec6-0bcbae2f18c4.png)

**Comment by the-simian** [comment]
![image](https://user-images.githubusercontent.com/954596/37730781-8612f736-2d0e-11e8-942d-62f8214a92e8.png)

**Comment by kacollins** [comment]
Looks like this was completed on March 21.
