### ISSUE TITLE
Arrange food, drink, and venue access for OKC JUG event | 01/10/2017 11:30 am

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/user-groups#73]
What: Topic TBD
When: 01/10/2017 11:30 am
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/okcjug/events/236354888/

**Comment by amandaharlin** [comment]
<img width="570" alt="screen shot 2017-01-10 at 10 07 49 am" src="https://cloud.githubusercontent.com/assets/716644/21813720/c4eeca1e-d71c-11e6-89b0-3e28f8fe1d6f.png">
