### ISSUE TITLE
Request to upload logo to Techlahoma Foundation LinkedIn page

### ISSUE THREAD

**Issue by wassimk** [techlahoma/user-groups#733]
Please upload a logo to the Techlahoma Foundation LinkedIn page:

https://www.linkedin.com/company/10152742/

**Comment by seejessicacode** [comment]
@DevinClark Can you take care of this or find someone who can?

**Comment by DevinClark** [comment]
@seejessicacode Yes. I'll hunt down who claimed the page.

**Comment by kacollins** [comment]
Has anyone made progress on figuring out how to access our LinkedIn page? @chimchim237?

**Comment by chimchim237** [comment]
Well, it's going to be one of these eight people:
https://www.linkedin.com/search/results/people/?facetCurrentCompany=%5B%2210152742%22%5D 

I have no idea who.
But I would guess it's probably one of the people on this list who would have been the original board members, since none of the current board members have access.

**Comment by chimchim237** [comment]
I would have said @DevinClark might know, but it sounds from above that he might have looked, and given up?  Or maybe he looked and found the answer and gave that answer to someone?

**Comment by kacollins** [comment]
@amandaharlin @vlucas @Avasond do you have access to Techlahoma's LinkedIn page or know who might?

**Comment by DevinClark** [comment]
@chimchim237 I looked and was unable to find anything.

**Comment by kacollins** [comment]
@DevinClark @chimchim237 has any progress made on this? We have volunteers who are willing to help if they can just get access.

**Comment by wassimk** [comment]
I just happened to be on LinkedIn and it looks like someone took care of it 🥇
