### ISSUE TITLE
Existing User Group Submission: Tulsa Mobile Dev

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#74]
**Agree to CoC:** Yes
**Group name:** Tulsa Mobile Dev
**Purpose:** 
**Current location:** Summit Club - Tulsa 
**Current meeting date and time:** Second Thursday of the month
**Leadership:** John Morad
Josh Barrow
Chris Condrey
Neil Lawrence
**Avg. # of attendees:** 28
**Avg. cost per meeting:** $900
**Who sponsors your group?:** Organizers' company
**Twitter:** tulsamobile
**Website:** http://tulsamobiledev.com/
**Would like help with:** General Mentorship, Social Media / Announcement, Connecting to the greater OK communtiy

Submitted by John Morad on 12/23/2016 18:32:27

**Comment by amandaharlin** [comment]
that's got to be a typo. bet he meant $90/meeting.

**Comment by groovecoder** [comment]
I emailed John.

**Comment by seejessicacode** [comment]
I couldn't find John Morad on GitHub, so I emailed him.

To: John (email hidden for privacy)
CC: info@techlahoma.org
From: Jessica Campbell's Techlahoma email (hidden for privacy)
Date Sent: 2/16/2017 7:39 am
> Hi John,
>
>I'm Jessica Campbell and I help lead Techlahoma's user group committee where we compile data unnecessary to help the board members review what it'll take to on-board a new or existing group and then help user group leaders join their groups to the Techlahoma family once the board votes them in.
>
>I have a question regarding [your application for Tulsa Mobile Dev](https://github.com/techlahoma/user-groups/issues/74).
>
>Average cost per meeting is $900. What does that cover? Who or who all is currently paying covering the meeting cost?
>
>It would be most beneficial to the Techlahoma board if you answered my questions at the GitHub issue linked above.
>
>Thank you,
>
>Jessica Campbell
>User Group Committee Member
>Techlahoma Foundation

**Comment by seejessicacode** [comment]
I forgot to request confirmation that Tulsa Mobile Devs doesn't want assistance with food. :(

**Comment by groovecoder** [comment]
I'm pretty sure they are meeting at their own company space and providing
all the food themselves. More likely they just want to be connected to the
rest of the tech community in Tulsa and OK.

-L

**Comment by groovecoder** [comment]
I'm meeting with John Morad next week to talk about 200 OK sponsorship. I'll also ask about Tulsa Mobile Devs & Techlahoma.

**Comment by seejessicacode** [comment]
Our board meeting is also next week, but we may not vote depending on financial review and board vote to onboard more groups. Just a heads up. Thanks @groovecoder!

**Comment by seejessicacode** [comment]
I'm going to close this due to lack of response from the applicant. Tulsa Mobile Dev is welcome to reapply if and when they interest in Techlahoma is revived.
