### ISSUE TITLE
Arrange food, drink, and venue access for OKGD event | 01/05/2017 7:00 pm

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#76]
What: Game Design Workshop
When: 01/05/2017 7:00 pm
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/Oklahoma-Game-Developers/events/236533423/

**Comment by seejessicacode** [comment]
> Looking like around 20 people with Meetup & FB combined. So, probably 5 large pizzas (3 pepperoni, 1 sausage, 1 cheese) and 3 sodas?
@goldfire

**Comment by amandaharlin** [comment]
can sodas should be in event center already (and totally saves some 💸). did you want 3 pep & 1 cheese?

**Comment by amandaharlin** [comment]
3 pep, 1 sausage, 1 feta+spinach ordered (just something different than cheese. if you really do want cheese please let me know and i'll get it ordered asap)

**Comment by goldfire** [comment]
👍  Thanks! Can soda is fine, I wasn't aware there was anything there already.
