### ISSUE TITLE
Book StarSpace46 for OKGD | 01/05/2017 7:00 pm

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#77]
What: Game Design Workshop
When: 01/05/2017 7:00 pm
Where: StarSpace 46

Check meetup for RSVP count: https://www.meetup.com/Oklahoma-Game-Developers/events/236533423/

**Comment by seejessicacode** [comment]
![image](https://cloud.githubusercontent.com/assets/943398/21565578/6c97f1f8-ce5f-11e6-8750-c3d8037df43c.png)
