### ISSUE TITLE
StarSpace46 User Group Leader Agreement Instructions

### ISSUE THREAD

**Issue by kacollins** [techlahoma/user-groups#776]
The accepted-sponsored email template says to review the StarSpace46 user group leader agreement but doesn't say what to do with it: https://github.com/techlahoma/user-groups/blame/75fe7568a00ed9cac6e0dcb3e1344baf0cabe8b2/email-templates/accepted-sponsored.md#L11

I believe that the last page needs to be signed and returned to outreach@techlahoma.org or to @Avasond  at StarSpace46.

**Comment by kacollins** [comment]
Change `Please also review the attached StarSpace46 User Group Leader Agreement.` to include instructions to sign the last page and return it to Ava at StarSpace46.

**Comment by linuxuser07** [comment]
I will work on this one. Thank you
