### ISSUE TITLE
Arrange food, drink, and venue access for OKC# event | 01/01/2018 11:30 am

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#78]
What: TBD
When: 01/01/2018 11:30 am
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/OKC-Sharp/events/swlthmyxcbcb/

**Comment by kacollins** [comment]
This meetup event has been deleted and will be re-created with the correct date later.
