### ISSUE TITLE
Update user group application forms

### ISSUE THREAD

**Issue by seejessicacode** [techlahoma/user-groups#8]
_Note: Copied from shared Evernote doc_
**Any group applying should provide the following:**
- User group name
- Description
- Organizer(s) bio and picture
- Organizer name and email
- Volunteers' names and emails
- Regular event agenda (is it a workshop, hack space, etc.--not social hour)
- Logo (if available)
- Facebook/Twitter/Meetup/Google+/etc. (if available)
- Website (if available)
- Photo of group meeting at a meetup (if available, used for promotion/ reports)
- Meetup days and location (if available, i.e. not new)
- Code of conduct (if available--for example, Code for OKC has Code for America's CoC)
- Another communities their meetup is a part of (if available--for example, Code for OKC is a Code for America group)
- Confirmation that they have read and agree to Techlahoma's code of conduct

**Comment by seejessicacode** [comment]
Since Squarespace does not have conditionally enabled form fields, I propose we divide the application fields among two forms similar to what we have now. One form for new user groups and the other for existing user groups.

**Fields for both new and existing user group applications:**
_All fields listed here are required_
- User group name
- Description
- The following info for organizer(s):
  - Name
  - Email
  - Bio
  - Picture
- The following info for volunteers:
  - Name
  - Email
- Regular event agenda (aka user group type, e.g. classroom, study hall, workshop, drink up, etc.)
- Confirmation that they have read and agreed to Techlahoma's code of conduct

**Fields for only new user group applications:**
- Logo (optional)
- Facebook/Twitter/Meetup/Meetup/Google+/etc. (optional)
- Website (optional)
- Preferred meetup days and location (required)

**Fields for only existing user group applications:**
- Logo (required)
- Facebook/Twitter/Meetup/Meetup/Google+/etc. (required)
- Website (optional)
- Photo of group meeting at a meetup (optional)
- Meetup days and location (required)
- Current code of conduct(s) (optional)
- Other communities associated with (optional)

**Comment by seejessicacode** [comment]
Been working on a test UG application on Squarespace. It's not done but feel free to view and adjust.

**Comment by the-simian** [comment]
Been really making a lot fo progress, here. Its all looking good so far

**Comment by seejessicacode** [comment]
I'm having the hardest time implementing these questionnaires in Squarespace. I'll try Google forms next.

**Comment by amandaharlin** [comment]
I can take a wack at this sometime soon.

**Comment by kacollins** [comment]
Need to ask whether the group is willing to use Meetup.com for RSVPs and to give Techlahoma the organizer role.

**Comment by kacollins** [comment]
It might be possible to update the applications to make it clearer that Techlahoma and StarSpace46 are not the same thing. I can see how phrases like "We offer event space" could be misleading.

**Comment by seejessicacode** [comment]
This is old and done.
