### ISSUE TITLE
Arrange food, drink, and venue access for Tulsa Web Devs event | 2018-01-02

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#80]
What: Hack Night
When: 2018-01-02 18:00
Where: 36 East Cameron St., Tulsa

Check meetup for RSVP count: https://www.meetup.com/Tulsa-Web-Devs/events/qjqkbmyxcbdb/

**Comment by groovecoder** [comment]
Wow, this is still 1 year away? @jsonthebson really likes to plan ahead ... @seejessicacode there might be a bug on this one?

**Comment by groovecoder** [comment]
Hmm ... yeah we can turn it off for us. I have my routine pretty much set, and all these future issues are turning this repo issues into a noisy fire-hose.

**Comment by seejessicacode** [comment]
Done
