### ISSUE TITLE
Update reimbursement comment bot (?) to send people to Venmo instead of cash.me

### ISSUE THREAD

**Issue by kendallcorner** [techlahoma/user-groups#804]
I looked into this a little, but I can't find creds for waffle.io.  Thanks!

**Comment by kacollins** [comment]
I just happened to see this issue. Are we using waffle.io? Can you give an example of what needs to be updated?

**Comment by kacollins** [comment]
@kendallcorner can you provide more information on what needs to be done for this?

**Comment by kacollins** [comment]
@kendallcorner does this still need to be done?
