### ISSUE TITLE
Arrange food, drink, and venue access for OKC.js event | 01/17/2017 11:30 am

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#83]
What: Distributed Systems and the Web
When: 01/17/2017 11:30 am
Where: , 

Check meetup for RSVP count: https://www.meetup.com/OKC-js/events/236655523/

**Comment by seejessicacode** [comment]
Yikes! I wonder why "Where" wasn't set to SS46. I created that event myself. My only reason for concern is that GH space issues are only made for events located at SS46, so no GH issue was created to remind me to book SS46. Well it's done now.

![image](https://cloud.githubusercontent.com/assets/943398/21661446/bec49038-d299-11e6-8758-7fbc9d68a1b5.png)
