### ISSUE TITLE
Book StarSpace46 for OKC Ruby | 01/12/2017 11:30 am

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#84]
What: DevOps Round Table
When: 01/12/2017 11:30 am
Where: StarSpace 46

Check meetup for RSVP count: https://www.meetup.com/OKC-Ruby/events/236678942/

**Comment by seejessicacode** [comment]
![image](https://cloud.githubusercontent.com/assets/943398/21661055/d542707a-d297-11e6-8972-ee3bb1dcf282.png)

**Comment by seejessicacode** [comment]
Ignore the price, SS46 isn't currently charging Techlahoma.
