### ISSUE TITLE
Book StarSpace46 for Code for OKC | 01/30/2017 6:00 pm

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#89]
What: January Hack Night
When: 01/30/2017 6:00 pm
Where: StarSpace46

Check meetup for RSVP count: https://www.meetup.com/Code-for-OKC/events/236712747/

**Comment by seejessicacode** [comment]
![image](https://cloud.githubusercontent.com/assets/943398/21727965/750be1dc-d409-11e6-8c11-ff3e5201722d.png)

**Comment by seejessicacode** [comment]
Event was rescheduled for the 23rd: https://github.com/techlahoma/user-groups/issues/88#issuecomment-272068607

**Comment by seejessicacode** [comment]
![image](https://cloud.githubusercontent.com/assets/943398/21891228/339ee52c-d897-11e6-870c-6f96784ad4d7.png)
