### ISSUE TITLE
Request reimbursement for food and drink for OKC Python event | 2018-06-13

### ISSUE THREAD

**Issue by kacollins** [techlahoma/user-groups#926]
What: Monthly Python Meeting
When: 06/13/2018
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/okcpython/events/vtdhfpyxjbrb/

To request reimbursement, please complete the following steps:
- [x] Post picture of receipt(s) in this thread
- [x] Post photo(s) of the meetup in action on your meetup event
- [x] Submit [request for reimbursement](https://github.com/techlahoma/user-groups/wiki/Requesting-Reimbursement) from the Techlahoma Foundation on https://venmo.com within 1 month of the event

Any questions about reimbursement may be referred to the board treasurer.

cc @mmattice, @kacollins, @tobynance

**Comment by kacollins** [comment]
![image](https://user-images.githubusercontent.com/15042297/41365685-aaf28aa2-6eff-11e8-925e-64cfbfa3a504.png)

**Comment by kacollins** [comment]
39 RSVPs earlier
![image](https://user-images.githubusercontent.com/15042297/41365720-c5f19bcc-6eff-11e8-87cd-35d37a54791f.png)

**Comment by kendallcorner** [comment]
Paid! I guess you just ran all the UGs last week!
