### ISSUE TITLE
Arrange food, drink, and venue access for OKC Python event | 01/10/2018 11:30 am

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/user-groups#94]
What: Monthly Python Meeting
When: 01/10/2018 11:30 am
Where: 1141 W Sheridan Ave, Oklahoma City

Check meetup for RSVP count: https://www.meetup.com/Oklahoma-City-Python-Users-Group/events/bzfcrlyxcbnb/

**Comment by amandaharlin** [comment]
done
