### ISSUE TITLE
Arrange food, drink, and venue access for OKC Python event | 01/11/2017 11:30 am

### ISSUE THREAD

**Issue by mmattice** [techlahoma/user-groups#96]
What: Python for baseball 2
When: 01/10/2018 11:30 am
Where: 1141 W Sheridan Ave, Oklahoma City

Current RSVP count: 14

**Comment by seejessicacode** [comment]
https://www.meetup.com/Oklahoma-City-Python-Users-Group/events/235706383/

**Comment by seejessicacode** [comment]
![screenshot_20170111-102039](https://cloud.githubusercontent.com/assets/943398/21856517/ed467fae-d7e7-11e6-900c-6f2b91fd9d26.png)
