### ISSUE TITLE
Book StarSpace46 for Big Data and Data Science | 02/02/2018 11:30 am

### ISSUE THREAD

**Issue by max522over** [techlahoma/user-groups#98]
What: Monthly Big Data and Data Science Meeting
When: 02/02/2018 11:30 am
Where: StarSpace 46

Check meetup for RSVP count: https://www.meetup.com/Big-Data-in-Oklahoma-City/

**Comment by seejessicacode** [comment]
Hi @max522over, 
We're still waiting on you to [make Techlahoma organizer of the meetup group](https://github.com/techlahoma/user-groups/wiki/Meetup#2a-ask-current-meetup-organizer-to-step-down-and-nominate-techlahoma-as-organizer). When you do then we can book SS46.

If you need further help, please contact @seejessicacode on slack.techlahoma.org.

**Comment by max522over** [comment]
I tried it again. Let me know if it worked.

**Comment by seejessicacode** [comment]
It worked! I'll begin adding Big Data in OKC to Techlahoma's website and task flow this weekend!

**Comment by seejessicacode** [comment]
I hope you meant 02/02/2017, instead of 2018... because that's when I booked SS46 for ya!
![image](https://cloud.githubusercontent.com/assets/943398/21914566/c79ab8d4-d8f9-11e6-9528-90b583740daa.png)
